import express from 'express';
import { randomBytes, randomUUID, createHash, scrypt as scryptCb, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { readFileSync, existsSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fsrs, createEmptyCard } from 'ts-fsrs';
import { openStore } from './store.mjs';
import { MODEL, updateBkt, readiness } from './models.mjs';
import { mailer } from './mail.mjs';
import { redactEvent } from './ai.mjs';
const scrypt = promisify(scryptCb), root = resolve(fileURLToPath(new URL('..',import.meta.url)));
const json = value => JSON.stringify(value), parse = (value,fallback=null) => value ? JSON.parse(value) : fallback;
const stamp = () => new Date().toISOString(), hash = value => createHash('sha256').update(value).digest('hex');
const normalized = value => String(value??'').normalize('NFKC').trim().replace(/\s+/g,' ').toLocaleLowerCase('es');
// ponytail: exact normalized fingerprints stop regenerated credit; add reviewed canonical item IDs if paraphrase equivalence must collapse too.
const assessmentId = q => `generated-${hash(json({objectiveId:q.objectiveId,objectiveVersion:String(q.objectiveVersion||'1'),type:q.type,prompt:normalized(q.prompt),correct:normalized(q.choices?.[q.answerIndex]),source:q.type==='fresh-transfer'?'':normalized(q.sourceSpan?.text)})).slice(0,32)}`;
const pubUser = u => u ? ({id:u.id,email:u.email,name:u.name,verified:!!u.verified,role:u.role}) : null;
const publicQuestion = q => q ? ({id:q.id,version:String(q.version || '1'),objectiveId:q.objectiveId,type:['multiple-choice','fresh-transfer','target-comprehension','target-form','target-vocabulary'].includes(q.type)?q.type:undefined,prompt:q.prompt,choices:q.choices}) : null;
const defaults = {theme:'system',fontSize:20,lineHeight:1.8};
function fail(status,code,message) {throw Object.assign(new Error(message),{status,code});}
function str(value,name,max=1000,min=1) {if(typeof value !== 'string' || value.trim().length < min || value.length > max) fail(400,'INVALID_INPUT',`${name} must contain ${min}–${max} characters.`); return value.trim();}
function attemptId(value) {return str(value,'attemptId',100,8);}
function validPassword(value) {if(typeof value !== 'string' || value.length < 12 || value.length > 128) fail(400,'INVALID_PASSWORD','Use a password between 12 and 128 characters.'); return value;}
async function passwordHash(password) {const salt=randomBytes(16).toString('hex');return `${salt}:${(await scrypt(password,salt,64)).toString('hex')}`;}
async function matches(password,stored) {const [salt,key]=stored.split(':'); const supplied=await scrypt(password,salt,64);return timingSafeEqual(Buffer.from(key,'hex'),supplied);}
const redact = redactEvent;
export function createApp(options={}) {
  const env=options.env || process.env, dataDir=resolve(options.dataDir || env.DATA_DIR || join(root,'runtime'));
  mkdirSync(join(dataDir,'uploads'),{recursive:true,mode:0o700});
  const db=openStore(options.dbPath || join(dataDir,'comelibro.sqlite'));
  const one=(sql,...args)=>db.prepare(sql).get(...args), all=(sql,...args)=>db.prepare(sql).all(...args), run=(sql,...args)=>db.prepare(sql).run(...args);
  const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}};
  const origin=env.APP_ORIGIN || 'http://localhost:3300', mail=mailer(env,options.mailSender);
  const app=express(); app.disable('x-powered-by'); app.set('trust proxy','loopback');
  const contentDir=options.contentDir || join(root,'content');
  const catalog=()=>{try{return JSON.parse(readFileSync(join(contentDir,'catalog.json'),'utf8'));}catch{ return {objectives:[],placement:[],lessons:[]};}};
  const publicBook=()=>{try{return {...JSON.parse(readFileSync(join(contentDir,'don-quixote.json'),'utf8')),kind:'public',status:'ready'};}catch{return null;}};
  const audit=(userId,kind,data,jobId=null)=>run('INSERT INTO events VALUES(?,?,?,?,?,?)',randomUUID(),userId,jobId,kind,json(redact(data)),stamp());
  const paused=()=>one("SELECT value FROM operational WHERE key='paused'")?.value === 'true';
  const throttle=(key,limit,seconds)=>{const now=Date.now();const row=one('SELECT * FROM throttles WHERE key=?',key);if(!row||row.expiresAt<=now)run('INSERT OR REPLACE INTO throttles VALUES(?,1,?)',key,now+seconds*1000);else{if(row.count>=limit)fail(429,'THROTTLED','Too many attempts. Please try again later.');run('UPDATE throttles SET count=count+1 WHERE key=?',key);}};
  const auth=(req,res,next)=>{if(!req.user)return next(Object.assign(new Error('Please sign in to continue.'),{status:401,code:'AUTH_REQUIRED'}));next();};
  const verified=(req,res,next)=>{if(!req.user?.verified)return next(Object.assign(new Error('Verify your email before starting this activity.'),{status:403,code:'EMAIL_UNVERIFIED'}));next();};
  const placed=(req,res,next)=>{if(parse(req.user.placement,{}).status!=='complete')return next(Object.assign(new Error('Finish your short placement check first.'),{status:409,code:'PLACEMENT_REQUIRED'}));next();};
  const admin=(req,res,next)=>{if(req.user?.role!=='admin')return next(Object.assign(new Error('Administrator access is required.'),{status:403,code:'ADMIN_REQUIRED'}));next();};
  app.use((req,res,next)=>{res.set({'X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'",'Permissions-Policy':'camera=(), microphone=(), geolocation=()'}); if(req.path.startsWith('/api'))res.set('Cache-Control','no-store'); next();});
  app.use('/api',(req,res,next)=>{if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.headers.origin!==origin)return next(Object.assign(new Error('This action must come from the Comelibro site.'),{status:403,code:'ORIGIN_DENIED'}));next();});
  app.use((req,res,next)=>{const cookie=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('comelibro_session='))?.slice(18); if(cookie){req.user=one('SELECT users.* FROM users JOIN sessions ON users.id=sessions.userId WHERE sessions.hash=? AND sessions.expiresAt>?',hash(cookie),stamp());req.sessionHash=hash(cookie);}next();});
  app.use('/api/books/upload',auth,verified,placed);
  app.use(express.json({limit:'1mb'}));
  function session(res,user) {const token=randomBytes(32).toString('base64url');run('INSERT INTO sessions VALUES(?,?,?)',hash(token),user.id,new Date(Date.now()+7*86400000).toISOString());res.cookie('comelibro_session',token,{httpOnly:true,secure:origin.startsWith('https:'),sameSite:'lax',path:'/',maxAge:7*86400000});}
  async function sendToken(user,kind) {const token=randomBytes(32).toString('base64url'); const result=await mail.send({email:user.email,kind,token,origin}); if(result.status==='sent')transaction(()=>{run('DELETE FROM tokens WHERE userId=? AND kind=?',user.id,kind);run('INSERT INTO tokens VALUES(?,?,?,?)',hash(token),user.id,kind,new Date(Date.now()+(kind==='verify'?86400000:1800000)).toISOString());});audit(user.id,'email',{kind,status:result.status});return result;}
  const quota=(id,kind)=>({used:one('SELECT count FROM quotas WHERE userId=? AND day=? AND kind=?',id,stamp().slice(0,10),kind)?.count || 0,limit:kind==='uploads'?3:50});
  function annotatedBook(book,user) {
    if(!user)return book;
    const curriculum=one('SELECT version,data FROM curricula WHERE userId=? AND bookId=? ORDER BY version DESC LIMIT 1',user.id,book.id),lessonIds=new Set(parse(curriculum?.data,{})?.lessons?.map(l=>l.id)||[]),objectives=new Map(catalog().objectives.map(o=>[o.id,String(o.version||'1')]));
    const chapters=(book.chapters||[]).map(chapter=>({...chapter,sentences:(chapter.sentences||[]).map(sentence=>({...sentence,tags:[...(sentence.tags||[])],objectiveSpans:(sentence.objectiveSpans||[]).map(a=>({...a,spans:[...a.spans]})),annotationProvenance:[...(sentence.annotationProvenance||[])]}))})),sentences=new Map(chapters.flatMap(c=>c.sentences.map(s=>[s.id,s])));
    if(curriculum)for(const row of all('SELECT id,data FROM lessons WHERE userId=? AND bookId=?',user.id,book.id)){if(!lessonIds.has(row.id))continue;const lesson=parse(row.data,{});if(!lesson.generated||lesson.id!==row.id||lesson.bookId!==book.id)continue;for(const q of lesson.questions||[]){const version=String(q.version||'1'),objectiveVersion=String(q.objectiveVersion||'1'),sentence=sentences.get(q.sourceSpan?.sentenceId);if(!lesson.objectiveIds?.includes(q.objectiveId)||objectives.get(q.objectiveId)!==objectiveVersion||!isReviewed(q)||!sentence||typeof q.sourceSpan.text!=='string'||!q.sourceSpan.text.trim()||!sentence.text.includes(q.sourceSpan.text))continue;let annotation=sentence.objectiveSpans.find(a=>a.objectiveId===q.objectiveId);if(!annotation){annotation={objectiveId:q.objectiveId,spans:[]};sentence.objectiveSpans.push(annotation);}if(!annotation.spans.includes(q.sourceSpan.text))annotation.spans.push(q.sourceSpan.text);if(!sentence.tags.includes(q.objectiveId))sentence.tags.push(q.objectiveId);const provenance={kind:'generated-reviewed',objectiveId:q.objectiveId,objectiveVersion,span:q.sourceSpan.text,curriculumVersion:curriculum.version,lessonId:lesson.id,questionId:q.id,questionVersion:version,review:{status:q.review.status,reviewer:q.review.reviewer,version:String(q.review.version)}};if(!sentence.annotationProvenance.some(p=>p.lessonId===provenance.lessonId&&p.questionId===provenance.questionId&&p.questionVersion===provenance.questionVersion))sentence.annotationProvenance.push(provenance);}}
    for(const chapter of chapters){const occurrences=new Map();for(const sentence of chapter.sentences)for(const annotation of sentence.objectiveSpans)for(const text of new Set(annotation.spans)){const locations=occurrences.get(annotation.objectiveId)||[];if(!locations.some(location=>location.sentenceId===sentence.id&&location.text===text))locations.push({sentenceId:sentence.id,text});occurrences.set(annotation.objectiveId,locations);}chapter.tags=[...new Set(chapter.sentences.flatMap(s=>s.tags))];chapter.objectiveOccurrences=[...occurrences].map(([objectiveId,locations])=>({objectiveId,count:locations.length,locations}));}
    return {...book,chapters};
  }
  function bookFor(id,user) {if(id==='don-quixote'){const book=publicBook();if(book)return annotatedBook(book,user);}const row=user&&one('SELECT * FROM books WHERE id=? AND userId=?',id,user.id);if(!row)fail(404,'BOOK_NOT_FOUND','This book is unavailable.');return annotatedBook({...parse(row.data),id:row.id,status:row.status,kind:'upload'},user);}
  function summaries(user) {const books=[publicBook(),...(user?all('SELECT * FROM books WHERE userId=? ORDER BY createdAt DESC',user.id).map(r=>({...parse(r.data),id:r.id,status:r.status,kind:'upload'})):[])].filter(Boolean);return books.map(b=>({id:b.id,title:b.title,author:b.author,kind:b.kind,status:b.status,chapterCount:b.chapters?.length || 0,sentenceCount:b.chapters?.reduce((n,c)=>n+(c.sentences?.length||0),0)||0,position:user?parse(one('SELECT data FROM positions WHERE userId=? AND bookId=?',user.id,b.id)?.data):null}));}
  function evidence(userId) {return catalog().objectives.map(o=>{const row=one('SELECT * FROM objectives WHERE userId=? AND objectiveId=? AND version=?',userId,o.id,String(o.version||'1'));return {...o,...readiness(row)};});}
  function placement(user) {const p=parse(user.placement,{}),questions=catalog().placement;return {status:p.status||'not_started',level:p.level||null,index:p.index||0,total:(p.questionIds||questions.map(q=>q.id)).length,question:p.status==='in_progress'?publicQuestion(questions.find(q=>q.id===p.questionIds[p.index])):null,objectives:evidence(user.id)};}
  const capabilities=()=>({ai:env.AI_PUBLIC_ENABLED==='true'&&existsSync(join(root,'server/ai.mjs')),pdf:existsSync(join(root,'server/pdf.mjs')),email:mail.configured,paused:paused()});
  app.get('/api/bootstrap',(req,res)=>res.json({user:pubUser(req.user),settings:{...defaults,...parse(req.user?.settings,{})},onboarding:req.user?placement(req.user):{status:'not_started',index:0,total:catalog().placement.length},books:summaries(req.user),dueReviews:req.user?one('SELECT count(*) AS n FROM vocabulary WHERE userId=? AND due<=?',req.user.id,stamp()).n:0,capabilities:capabilities(),quotas:req.user?{uploads:quota(req.user.id,'uploads'),help:quota(req.user.id,'help')}:null}));
  app.post('/api/auth/register',async(req,res)=>{throttle(`signup:${req.ip}`,5,3600);const email=str(req.body.email,'Email',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'INVALID_EMAIL','Enter a valid email address.');const name=str(req.body.name||'Reader','Name',80);const password=await passwordHash(validPassword(req.body.password));if(one('SELECT id FROM users WHERE email=?',email))fail(409,'ACCOUNT_EXISTS','This email is already registered. Sign in or reset your password.');const user={id:randomUUID(),email,name,password,verified:0,role:(env.ADMIN_EMAILS||'').toLowerCase().split(',').map(v=>v.trim()).includes(email)?'admin':'learner'};run('INSERT INTO users(id,email,name,password,role,createdAt) VALUES(?,?,?,?,?,?)',user.id,email,name,password,user.role,stamp());session(res,user);const emailStatus=await sendToken(user,'verify');audit(user.id,'transition',{node:'account',event:'register',from:'anonymous',to:'unverified'});res.status(201).json({user:pubUser(user),email:emailStatus});});
  app.post('/api/auth/login',async(req,res)=>{throttle(`login:${req.ip}`,20,900);const email=str(req.body.email,'Email',254).toLowerCase(),password=validPassword(req.body.password);const user=one('SELECT * FROM users WHERE email=?',email);const dummy='0123456789abcdef0123456789abcdef:'+Buffer.alloc(64).toString('hex');if(!await matches(password,user?.password||dummy)||!user)fail(401,'INVALID_CREDENTIALS','Email or password is incorrect.');if(req.sessionHash)run('DELETE FROM sessions WHERE hash=?',req.sessionHash);session(res,user);res.json({user:pubUser(user)});});
  app.post('/api/auth/logout',(req,res)=>{if(req.sessionHash)run('DELETE FROM sessions WHERE hash=?',req.sessionHash);res.clearCookie('comelibro_session',{path:'/'});res.json({ok:true});});
  app.post('/api/auth/resend-verification',auth,async(req,res)=>{throttle(`resend:${req.user.id}`,3,3600);res.json({email:await sendToken(req.user,'verify')});});
  app.post('/api/auth/verify',(req,res)=>{const token=str(req.body.token,'Verification token',150);const row=one("SELECT * FROM tokens WHERE hash=? AND kind='verify' AND expiresAt>?",hash(token),stamp());if(!row)fail(400,'TOKEN_INVALID','This verification link is invalid or expired. Request a new one.');transaction(()=>{run('UPDATE users SET verified=1 WHERE id=?',row.userId);run('DELETE FROM tokens WHERE hash=?',hash(token));});const user=one('SELECT * FROM users WHERE id=?',row.userId);if(req.sessionHash)run('DELETE FROM sessions WHERE hash=?',req.sessionHash);session(res,user);res.json({ok:true,user:pubUser(user)});});
  app.post('/api/auth/forgot-password',async(req,res)=>{throttle(`forgot:${req.ip}`,5,3600);const email=str(req.body.email,'Email',254).toLowerCase(),user=one('SELECT * FROM users WHERE email=?',email);if(user)await sendToken(user,'reset');res.json({ok:true,message:'If an account exists and email delivery is available, a reset link has been sent. Check your inbox or try again later.'});});
  app.post('/api/auth/reset-password',async(req,res)=>{throttle(`reset:${req.ip}`,10,3600);const token=str(req.body.token,'Reset token',150);const password=await passwordHash(validPassword(req.body.password));const row=one("SELECT * FROM tokens WHERE hash=? AND kind='reset' AND expiresAt>?",hash(token),stamp());if(!row)fail(400,'TOKEN_INVALID','This reset link is invalid or expired. Request a new one.');transaction(()=>{run('UPDATE users SET password=? WHERE id=?',password,row.userId);run('DELETE FROM sessions WHERE userId=?',row.userId);run('DELETE FROM tokens WHERE userId=?',row.userId);});res.clearCookie('comelibro_session',{path:'/'});res.json({ok:true});});
  app.patch('/api/settings',auth,(req,res)=>{const b=req.body;const settings={...defaults,...parse(req.user.settings,{})};if(b.theme!==undefined){if(!['light','dark','system'].includes(b.theme))fail(400,'INVALID_INPUT','Choose light, dark, or system theme.');settings.theme=b.theme;}for(const [key,min,max] of [['fontSize',16,32],['lineHeight',1.3,2.4]])if(b[key]!==undefined){if(typeof b[key]!=='number'||b[key]<min||b[key]>max)fail(400,'INVALID_INPUT',`${key} is outside the supported range.`);settings[key]=b[key];}run('UPDATE users SET settings=? WHERE id=?',json(settings),req.user.id);res.json({settings});});
  function isReviewed(question) {return question.review?.status==='approved' && !!question.review.reviewer && String(question.review.version)===String(question.version||'1');}
  function assessmentAliases(user) {
    // Keep old lesson IDs, responses and BKT history intact; their retained snapshots identify prior exposure.
    // ponytail: scans this account's lesson history; persist indexed aliases if histories make this expensive.
    const aliases=new Map();
    for(const row of all('SELECT data FROM lessons WHERE userId=?',user.id))for(const q of parse(row.data).questions||[]){
      if(!q.id.startsWith('generated-'))continue;
      const id=assessmentId(q);if(!aliases.has(id))aliases.set(id,new Set([id]));aliases.get(id).add(q.id);
    }
    return aliases;
  }
  const questionIds=(q,aliases)=>q.id.startsWith('generated-')?aliases.get(assessmentId(q))||new Set([q.id]):new Set([q.id]);
  function score(user,q,body,context) {
    const id=attemptId(body.attemptId),version=String(q.version||'1');
    if(!Number.isInteger(body.choiceIndex)||body.choiceIndex<0||body.choiceIndex>=q.choices.length)fail(400,'INVALID_ANSWER','Choose one of the answers.');
    if(body.assisted!==undefined&&typeof body.assisted!=='boolean')fail(400,'INVALID_INPUT','assisted must be true or false.');
    if(body.elapsedMs!==undefined&&(!Number.isInteger(body.elapsedMs)||body.elapsedMs<0||body.elapsedMs>86400000))fail(400,'INVALID_INPUT','Invalid answer timing.');
    const duplicate=one('SELECT * FROM attempts WHERE userId=? AND id=?',user.id,id);
    if(duplicate){if(duplicate.questionId!==q.id||duplicate.questionVersion!==version||duplicate.choiceIndex!==body.choiceIndex||duplicate.context!==context)fail(409,'ATTEMPT_CONFLICT','This attempt identifier was already used for a different answer.');return {...parse(duplicate.response),duplicate:true};}
    const generated=q.id.startsWith('generated-'),ids=json([...questionIds(q,generated?assessmentAliases(user):new Map())]);
    const first=!one('SELECT id FROM attempts WHERE userId=? AND questionId IN (SELECT value FROM json_each(?))',user.id,ids);
    const previousAssistance=generated?one('SELECT kind FROM assistance WHERE userId=? AND questionId IN (SELECT value FROM json_each(?))',user.id,ids):one('SELECT kind FROM assistance WHERE userId=? AND questionId=? AND questionVersion=?',user.id,q.id,version);
    const assisted=!!body.assisted||!!previousAssistance;
    const objective=catalog().objectives.find(o=>o.id===q.objectiveId&&String(o.version||'1')===String(q.objectiveVersion||'1'));
    const scored=first&&!assisted&&isReviewed(q)&&!!objective;
    const correct=body.choiceIndex===q.answerIndex;
    let estimate=null;
    if(scored){const ov=String(objective.version||'1');const prior=one('SELECT * FROM objectives WHERE userId=? AND objectiveId=? AND version=?',user.id,objective.id,ov);const probability=updateBkt(prior?.probability??MODEL.prior,correct);
      const successes=(prior?.successes||0)+(correct?1:0), itemCount=one('SELECT count(DISTINCT questionId) AS n FROM attempts WHERE userId=? AND objectiveId=? AND objectiveVersion=? AND scored=1 AND correct=1',user.id,objective.id,ov).n+(correct?1:0);
      const row={probability,successes,itemCount,updatedAt:stamp()};
      run('INSERT OR REPLACE INTO objectives VALUES(?,?,?,?,?,?,?)',user.id,objective.id,ov,probability,successes,itemCount,row.updatedAt);
      run('INSERT INTO bkt_history VALUES(?,?,?,?,?,?)',randomUUID(),user.id,id,objective.id,json({prior:prior?.probability??MODEL.prior,posterior:probability,correct,questionId:q.id,questionVersion:version,objectiveVersion:ov,parameters:MODEL,assisted:false}),stamp());
      estimate={id:objective.id,...readiness(row)};
    }
    const response={correct,explanation:q.explanation||'',scored,duplicate:false,objective:estimate};
    run('INSERT INTO attempts VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,user.id,q.id,version,q.objectiveId||null,String(q.objectiveVersion||'1'),context,body.choiceIndex,Number(correct),Number(assisted),Number(scored),body.elapsedMs??null,stamp(),json(response));
    audit(user.id,'transition',{node:context,event:'answer',from:'question',to:'feedback',attemptId:id,scored,correct,assisted});
    return response;
  }
  app.get('/api/placement',auth,verified,(req,res)=>res.json(placement(req.user)));
  app.post('/api/placement/start',auth,verified,(req,res)=>{const level=str(req.body.level,'Level',30);if(!['beginner','elementary','intermediate','advanced'].includes(level))fail(400,'INVALID_LEVEL','Choose the description that best matches your Spanish.');const existing=parse(req.user.placement,{});if(!existing.status){const questions=[...catalog().placement].sort((a,b)=>Math.abs((a.difficulty||1)-({beginner:1,elementary:2,intermediate:3,advanced:4}[level]))-Math.abs((b.difficulty||1)-({beginner:1,elementary:2,intermediate:3,advanced:4}[level]))||a.id.localeCompare(b.id));if(!questions.length)fail(503,'CONTENT_UNAVAILABLE','The placement check is temporarily unavailable.');const p={status:'in_progress',level,index:0,bankVersion:catalog().version||'1',questionIds:questions.map(q=>q.id)};run('UPDATE users SET placement=? WHERE id=?',json(p),req.user.id);req.user.placement=json(p);}res.json(placement(req.user));});
  app.post('/api/placement/answer',auth,verified,(req,res)=>{const p=parse(req.user.placement,{}),questions=catalog().placement;const question=questions.find(q=>q.id===req.body.questionId);if(!question)fail(404,'QUESTION_NOT_FOUND','This question is unavailable.');const duplicate=one('SELECT id FROM attempts WHERE userId=? AND id=?',req.user.id,attemptId(req.body.attemptId));if(!duplicate&&(p.status!=='in_progress'||p.questionIds[p.index]!==question.id))fail(409,'QUESTION_OUT_OF_ORDER','Resume the current placement question.');const result=transaction(()=>{const result=score(req.user,question,req.body,'placement');if(!result.duplicate){p.index++;if(p.index>=p.questionIds.length)p.status='complete';run('UPDATE users SET placement=? WHERE id=?',json(p),req.user.id);req.user.placement=json(p);}return result;});res.json({...result,placement:placement(req.user)});});
  app.get('/api/sample.pdf',(req,res)=>res.download(join(contentDir,'fixtures','sample-text.pdf'),'comelibro-sample.pdf'));
  app.get('/api/sample-scan.pdf',(req,res)=>res.download(join(contentDir,'fixtures','sample-scan.pdf'),'comelibro-sample-scan.pdf'));
  app.get('/api/books',(req,res)=>res.json({books:summaries(req.user)}));
  app.get('/api/books/:id',(req,res)=>res.json({book:bookFor(req.params.id,req.user)}));
  function passagesFor(book) {
    const sentences=(book.chapters||[]).flatMap(c=>c.sentences||[]),declared=(book.passages||[]).map(p=>({...p,sentences:sentences.filter(s=>p.sentenceIds?.includes(s.id))}));
    // ponytail: 40-sentence retrieval windows fit the adapter; use paragraph boundaries when source metadata records them.
    const windows=(book.chapters||[]).flatMap(chapter=>{const source=chapter.sentences||[];if(!source.length)return [];if(source.length<=40)return [{...chapter,chapterId:chapter.id,kind:'chapter'}];const parts=[];for(let start=0;start<source.length;start+=40){const part=source.slice(start,start+40);parts.push({id:`${chapter.id}-window-${parts.length+1}`,title:`${chapter.title} · sentences ${start+1}–${start+part.length}`,chapterId:chapter.id,kind:'chapter-window',startSentence:start+1,endSentence:start+part.length,sentences:part});}return parts;});
    return [...declared,...windows];
  }
  app.get('/api/books/:id/passages',(req,res)=>{const book=bookFor(req.params.id,req.user);res.json({passages:passagesFor(book).filter(c=>!req.query.chapter||c.chapterId===req.query.chapter)});});
  function sourceSentence(book,id){const chapter=book.chapters?.find(c=>c.sentences?.some(s=>s.id===id));const sentence=chapter?.sentences.find(s=>s.id===id);if(!sentence)fail(404,'SENTENCE_NOT_FOUND','This sentence is unavailable.');return {chapter,sentence};}
  app.post('/api/books/:id/position',auth,(req,res)=>{const book=bookFor(req.params.id,req.user);const {chapter,sentence}=sourceSentence(book,req.body.sentenceId);if(chapter.id!==req.body.chapterId)fail(400,'INVALID_POSITION','The sentence does not belong to this chapter.');run('INSERT OR REPLACE INTO positions VALUES(?,?,?)',req.user.id,book.id,json({chapterId:chapter.id,sentenceId:sentence.id,updatedAt:stamp()}));res.json({ok:true});});
  const jobView=row=>row?{id:row.id,kind:row.kind,bookId:row.bookId,status:row.status,progress:row.progress,message:redact(row.message),result:redact(parse(row.result)),error:redact(row.error),createdAt:row.createdAt,updatedAt:row.updatedAt}:null;
  let active=null,workerRunning=false;
  function ownedJob(id,user){const row=user.verified&&user.role==='admin'?one('SELECT * FROM jobs WHERE id=?',id):one('SELECT * FROM jobs WHERE id=? AND userId=?',id,user.id);if(!row)fail(404,'JOB_NOT_FOUND','This processing request is unavailable.');return row;}
  function enqueue(user,kind,bookId,input,key,quotaKind) {
    if(key)str(key,'Idempotency-Key',100,8);
    const prior=key&&one('SELECT * FROM jobs WHERE userId=? AND kind=? AND idempotencyKey=?',user.id,kind,key);
    if(prior){if(prior.bookId!==bookId && kind!=='upload'||prior.input!==json(input))fail(409,'IDEMPOTENCY_CONFLICT','This request key was already used for different content.');return {job:jobView(prior),duplicate:true};}
    if(paused())fail(503,'PROCESSING_PAUSED','Processing is paused. Reading and existing lessons remain available.');
    if(one("SELECT count(*) AS n FROM jobs WHERE status IN ('queued','running')").n>=20)fail(429,'QUEUE_FULL','The processing queue is full. Please try again shortly.');
    const q=quotaKind&&quota(user.id,quotaKind);if(q&&q.used>=q.limit)fail(429,'QUOTA_EXCEEDED',`You have reached today's limit of ${q.limit} ${quotaKind==='uploads'?'uploads':'help requests'}. It resets at midnight UTC.`);
    if(kind==='curriculum'&&one("SELECT count(*) AS n FROM jobs WHERE userId=? AND kind='curriculum' AND createdAt>=?",user.id,stamp().slice(0,10)).n>=20)fail(429,'CURRICULUM_LIMIT','You have reached today’s limit of 20 curriculum requests.');
    const id=randomUUID(),now=stamp();
    transaction(()=>{if(quotaKind)run('INSERT INTO quotas VALUES(?,?,?,1) ON CONFLICT(userId,day,kind) DO UPDATE SET count=count+1',user.id,now.slice(0,10),quotaKind);run('INSERT INTO jobs(id,userId,bookId,kind,status,input,idempotencyKey,createdAt,updatedAt) VALUES(?,?,?,?,?,?,?,?,?)',id,user.id,bookId,kind,'queued',json(input),key||null,now,now);audit(user.id,'transition',{node:'job',event:'enqueue',from:null,to:'queued'},id);});
    return {job:jobView(one('SELECT * FROM jobs WHERE id=?',id)),duplicate:false};
  }
  app.post('/api/books/upload',express.raw({type:'application/pdf',limit:5*1024*1024}),(req,res)=>{if(!Buffer.isBuffer(req.body)||req.body.length<5||req.body.subarray(0,5).toString()!=='%PDF-')fail(422,'INVALID_PDF','Upload a valid PDF file using application/pdf.');let filename;try{filename=decodeURIComponent(req.get('X-Filename')||'Spanish document.pdf');}catch{fail(400,'INVALID_FILENAME','The filename could not be read.');}filename=str(filename,'Filename',180).replace(/[\\/\x00-\x1f]/g,'_');const key=req.get('Idempotency-Key'),digest=hash(req.body);const prior=key&&one("SELECT * FROM jobs WHERE userId=? AND kind='upload' AND idempotencyKey=?",req.user.id,key);if(prior){const previous=parse(prior.input);if(previous.digest!==digest||previous.filename!==filename)fail(409,'IDEMPOTENCY_CONFLICT','This upload key belongs to a different file.');return res.status(202).json({job:jobView(prior),bookId:prior.bookId});}const id=randomUUID(),path=join(dataDir,'uploads',id+'.pdf');const result=enqueue(req.user,'upload',id,{path,filename,digest},key,'uploads');try{writeFileSync(path,req.body,{mode:0o600});run('INSERT INTO books VALUES(?,?,?,?,?,?)',id,req.user.id,json({id,title:filename.replace(/\.pdf$/i,''),author:'Your upload',chapters:[],extractionWarnings:[]}), 'processing',path,stamp());}catch(error){rmSync(path,{force:true});run("UPDATE jobs SET status='failed',error='The file could not be saved.' WHERE id=?",result.job.id);throw error;}res.status(202).json({...result,bookId:id});});
  app.get('/api/jobs/:id',auth,(req,res)=>res.json({job:jobView(ownedJob(req.params.id,req.user))}));
  app.post('/api/jobs/:id/cancel',auth,(req,res)=>{const job=ownedJob(req.params.id,req.user);if(['queued','running'].includes(job.status)){run("UPDATE jobs SET status='cancelled',message='Cancelled. You can try again.',updatedAt=? WHERE id=?",stamp(),job.id);if(job.kind==='upload')run("UPDATE books SET status='cancelled' WHERE id=?",job.bookId);audit(req.user.id,'transition',{node:'job',event:'cancel',from:job.status,to:'cancelled'},job.id);if(active?.id===job.id)active.controller.abort();}res.json({job:jobView(ownedJob(job.id,req.user))});});
  function chaptersFromPages(id,pages) {return pages.map(p=>({id:`${id}-page-${p.page}`,title:`Page ${p.page}`,page:p.page,sentences:p.text.split(/(?<=[.!?])\s+(?=[A-ZÁÉÍÓÚÜÑ¿¡])/u).filter(Boolean).map((text,i)=>({id:`${id}-p${p.page}-s${i+1}`,text,page:p.page,tags:[]}))}));}
  app.post('/api/books/:id/confirm',auth,verified,placed,(req,res)=>{const book=bookFor(req.params.id,req.user);if(book.kind!=='upload')fail(409,'CONFIRMATION_UNNEEDED','This public-domain book is already available.');if(!['needs_confirmation','ready'].includes(book.status))fail(409,'EXTRACTION_NOT_READY','Wait for extraction to finish before confirming the text.');const pages=req.body.pages||book.pages;if(!Array.isArray(pages)||!pages.length||pages.length>10||pages.some((p,i)=>!Number.isInteger(p.page)||p.page!==i+1||typeof p.text!=='string'||p.text.length>80000)||!pages.some(p=>p.text.trim()))fail(400,'INVALID_PAGES','Confirm one to ten numbered pages with some readable Spanish text. Blank source pages may remain blank.');if(book.status==='ready'){if(json(pages)!==json(book.pages))fail(409,'SOURCE_LOCKED','Confirmed source text cannot be changed. Upload a new document for corrected text.');return res.json({book});}const updated={...book,pages,chapters:chaptersFromPages(book.id,pages),confirmedAt:stamp(),status:'ready'};run('UPDATE books SET data=?,status=? WHERE id=? AND userId=?',json(updated),'ready',book.id,req.user.id);audit(req.user.id,'transition',{node:'document',event:'confirm',from:book.status,to:'ready',bookId:book.id});res.json({book:updated});});
  function lessonFor(id,user) {const row=one('SELECT * FROM lessons WHERE id=? AND userId=?',id,user.id);const lesson=row?parse(row.data):catalog().lessons.find(l=>l.id===id);if(!lesson)fail(404,'LESSON_NOT_FOUND','This lesson is unavailable.');bookFor(lesson.bookId,user);return lesson;}
  function progress(user,lesson) {
    const attempts=all('SELECT * FROM attempts WHERE userId=? AND context=? ORDER BY createdAt',user.id,`lesson:${lesson.id}`);
    const responses=lesson.questions.flatMap(q=>{const row=attempts.find(r=>r.questionId===q.id&&r.questionVersion===String(q.version||'1'));return row?[{questionId:q.id,choiceIndex:row.choiceIndex,correct:!!row.correct,scored:!!row.scored,assisted:!!row.assisted,explanation:parse(row.response).explanation}]:[];});
    const aliases=lesson.questions.some(q=>q.id.startsWith('generated-'))?assessmentAliases(user):new Map(),help=all('SELECT * FROM assistance WHERE userId=?',user.id);
    const assistance=lesson.questions.flatMap(q=>{const ids=questionIds(q,aliases),rows=help.filter(row=>ids.has(row.questionId)&&(q.id.startsWith('generated-')||String(q.version||'1')===row.questionVersion)),row=rows.find(row=>row.kind==='reveal')||rows[0];return row?[{questionId:q.id,kind:row.kind,...(row.kind==='reveal'?{answerIndex:q.answerIndex,explanation:q.explanation}:{hint:q.hint||'Compare each choice with the source passage.'})}]:[];});
    return {answered:responses.length,correct:responses.filter(r=>r.correct).length,total:lesson.questions.length,responses,assistance};
  }
  function lessonSummary(lesson,user){let current=lesson;if(!current.questions)current=parse(one('SELECT data FROM lessons WHERE id=? AND userId=?',lesson.id,user.id)?.data)||catalog().lessons.find(l=>l.id===lesson.id)||lesson;const answered=current.questions?.length?progress(user,current).answered:0;return {id:lesson.id,title:lesson.title,passageId:lesson.passageId,objectiveIds:lesson.objectiveIds,estimatedMinutes:lesson.estimatedMinutes||6,status:answered===current.questions?.length?'complete':answered?'in_progress':'available'};}
  function curriculumFor(book,user) {const row=one('SELECT * FROM curricula WHERE userId=? AND bookId=? ORDER BY version DESC LIMIT 1',user.id,book.id);if(row){const data=parse(row.data);return {...data,lessons:data.lessons.map(l=>lessonSummary(l,user)),objectives:evidence(user.id)};}const lessons=catalog().lessons.filter(l=>l.bookId===book.id);if(!lessons.length)return null;return {version:1,title:`Read ${book.title}`,reason:'Build understanding of the opening passage through short, independently reviewed checks.',lessons:lessons.map(l=>lessonSummary(l,user)),objectives:evidence(user.id)};}
  app.get('/api/books/:id/curriculum',auth,verified,placed,(req,res)=>{const book=bookFor(req.params.id,req.user);res.json({curriculum:curriculumFor(book,req.user),jobs:all("SELECT * FROM jobs WHERE userId=? AND bookId=? AND kind='curriculum' ORDER BY createdAt DESC LIMIT 10",req.user.id,book.id).map(jobView)});});
  app.post('/api/books/:id/curriculum',auth,verified,placed,(req,res)=>{const book=bookFor(req.params.id,req.user);if(book.status!=='ready')fail(409,'CONFIRMATION_REQUIRED','Confirm the extracted text before building a study plan.');if(!capabilities().ai&&!options.aiAdapter)fail(503,'AI_UNAVAILABLE','Live AI is currently unavailable. The reader and existing lessons remain available.');const passage=passagesFor(book).find(c=>c.id===req.body.passageId)||(!req.body.passageId&&passagesFor(book)[0]);if(!passage)fail(404,'PASSAGE_NOT_FOUND','Choose a passage in this book.');const result=enqueue(req.user,'curriculum',book.id,{passageId:passage.id},req.get('Idempotency-Key'));res.status(202).json(result);});
  app.get('/api/lessons/:id',auth,verified,placed,(req,res)=>{const lesson=lessonFor(req.params.id,req.user),ids=new Set(lesson.glossaryIds||[]),glossary=(catalog().glossary||[]).filter(g=>ids.has(g.id)&&g.version!==undefined&&g.review?.status==='approved'&&g.review.reviewer&&String(g.review.version)===String(g.version)).map(({id,version,term,meaning,sourceId})=>({id,version:String(version),term,meaning,sourceId}));res.json({lesson:{...lesson,glossary,questions:lesson.questions.map(publicQuestion)},progress:progress(req.user,lesson),objectiveEvidence:evidence(req.user.id).filter(o=>lesson.objectiveIds.includes(o.id))});});
  app.post('/api/lessons/:id/answer',auth,verified,placed,(req,res)=>{const lesson=lessonFor(req.params.id,req.user),question=lesson.questions.find(q=>q.id===req.body.questionId);if(!question)fail(404,'QUESTION_NOT_FOUND','This question is unavailable.');const result=transaction(()=>score(req.user,question,req.body,`lesson:${lesson.id}`));res.json({...result,progress:progress(req.user,lesson)});});
  app.post('/api/lessons/:id/assist',auth,verified,placed,(req,res)=>{const lesson=lessonFor(req.params.id,req.user),question=lesson.questions.find(q=>q.id===req.body.questionId);if(!question)fail(404,'QUESTION_NOT_FOUND','This question is unavailable.');if(!['hint','reveal'].includes(req.body.kind))fail(400,'INVALID_INPUT','Choose a hint or answer reveal.');run("INSERT INTO assistance VALUES(?,?,?,?,?) ON CONFLICT(userId,questionId,questionVersion) DO UPDATE SET kind=CASE WHEN excluded.kind='reveal' THEN 'reveal' ELSE assistance.kind END",req.user.id,question.id,String(question.version||'1'),req.body.kind,stamp());res.json(req.body.kind==='reveal'?{answerIndex:question.answerIndex,explanation:question.explanation}:{hint:question.hint||'Look at the source passage and compare each choice. Using a hint makes this practice rather than an unaided check.'});});
  app.post('/api/books/:id/help',auth,verified,(req,res)=>{const book=bookFor(req.params.id,req.user),{sentence}=sourceSentence(book,req.body.sentenceId);if(!['word','explain','translate'].includes(req.body.kind))fail(400,'INVALID_INPUT','Choose a word meaning, explanation, or translation.');const word=req.body.kind==='word'?str(req.body.word,'Word',100):null;if(word&&!sentence.text.toLocaleLowerCase('es').includes(word.toLocaleLowerCase('es')))fail(400,'INVALID_WORD','Choose a word from this sentence.');if(!capabilities().ai&&!options.aiAdapter)fail(503,'AI_UNAVAILABLE','AI reading help is currently unavailable. You can still read and save vocabulary.');const result=enqueue(req.user,'help',book.id,{sentenceId:sentence.id,kind:req.body.kind,word},req.get('Idempotency-Key'),'help');res.status(202).json(result);});
  const scheduler=fsrs({request_retention:0.9,enable_fuzz:false});
  const itemView=row=>({id:row.id,front:row.front,back:row.back,bookId:row.bookId,sentenceId:row.sentenceId,due:row.due});
  app.post('/api/vocabulary',auth,verified,(req,res)=>{const book=bookFor(str(req.body.bookId,'Book',150),req.user);sourceSentence(book,req.body.sentenceId);const front=str(req.body.front,'Word or phrase',200),back=str(req.body.back,'Meaning',1000);const previous=one('SELECT * FROM vocabulary WHERE userId=? AND front=? AND back=?',req.user.id,front,back);if(previous)return res.status(200).json({item:itemView(previous)});const id=randomUUID(),now=stamp(),card=createEmptyCard(new Date());run('INSERT INTO vocabulary VALUES(?,?,?,?,?,?,?,?,?)',id,req.user.id,book.id,req.body.sentenceId,front,back,json(card),card.due.toISOString(),now);res.status(201).json({item:itemView(one('SELECT * FROM vocabulary WHERE id=?',id))});});
  app.get('/api/reviews',auth,verified,(req,res)=>{const items=all('SELECT * FROM vocabulary WHERE userId=? AND due<=? ORDER BY due LIMIT 100',req.user.id,stamp());res.json({items:items.map(itemView),dueCount:one('SELECT count(*) AS n FROM vocabulary WHERE userId=? AND due<=?',req.user.id,stamp()).n,total:one('SELECT count(*) AS n FROM vocabulary WHERE userId=?',req.user.id).n});});
  app.post('/api/reviews/:id',auth,verified,(req,res)=>{const row=one('SELECT * FROM vocabulary WHERE id=? AND userId=?',req.params.id,req.user.id);if(!row)fail(404,'ITEM_NOT_FOUND','This saved item is unavailable.');const id=attemptId(req.body.attemptId),rating=req.body.rating;if(![1,2,3,4].includes(rating))fail(400,'INVALID_RATING','Choose Again, Hard, Good, or Easy.');const prior=one('SELECT * FROM reviews WHERE userId=? AND id=?',req.user.id,id);if(prior){const data=parse(prior.data);if(prior.itemId!==row.id||data.rating!==rating)fail(409,'ATTEMPT_CONFLICT','This review identifier belongs to a different review.');return res.json({item:data.item,duplicate:true});}if(row.due>stamp())fail(409,'REVIEW_NOT_DUE','This item is not due yet.');const card=parse(row.card);card.due=new Date(card.due);if(card.last_review)card.last_review=new Date(card.last_review);const next=scheduler.next(card,new Date(),rating);const item={...itemView(row),due:next.card.due.toISOString()};transaction(()=>{run('UPDATE vocabulary SET card=?,due=? WHERE id=?',json(next.card),item.due,row.id);run('INSERT INTO reviews VALUES(?,?,?,?,?)',id,req.user.id,row.id,json({rating,item,card:next.card,log:next.log,scheduler:'ts-fsrs',bktUpdated:false}),stamp());});res.json({item,duplicate:false});});
  app.post('/api/feedback',auth,(req,res)=>{const message=str(req.body.message,'Report',3000);if(req.body.bookId)bookFor(req.body.bookId,req.user);if(req.body.lessonId)lessonFor(req.body.lessonId,req.user);const id=randomUUID();run('INSERT INTO review_queue VALUES(?,?,?,?,?,?,?,?)',id,req.user.id,req.body.bookId||null,'feedback','pending',json(redact({message,lessonId:req.body.lessonId||null,sentenceId:req.body.sentenceId||null})),null,stamp());res.status(201).json({id,status:'pending'});});
  app.use('/api/admin',auth,verified,admin);
  app.get('/api/admin/overview',(req,res)=>res.json({counts:{accounts:one('SELECT count(*) AS n FROM users').n,jobs:one('SELECT count(*) AS n FROM jobs').n,pending:one("SELECT count(*) AS n FROM review_queue WHERE status='pending'").n,failures:one("SELECT count(*) AS n FROM jobs WHERE status='failed'").n},paused:paused(),quotas:all('SELECT * FROM quotas WHERE day=?',stamp().slice(0,10)),model:MODEL,retention:{operationalLogDays:30,accountData:'Retained while account is active; authenticated account deletion removes private data.'}}));
  app.get('/api/admin/accounts',(req,res)=>res.json({accounts:all('SELECT id,email,name,verified,role,createdAt FROM users ORDER BY createdAt DESC')}));
  app.get('/api/admin/accounts/:id',(req,res)=>{const account=one('SELECT * FROM users WHERE id=?',req.params.id);if(!account)fail(404,'ACCOUNT_NOT_FOUND','Account not found.');res.json(redact({account:{...pubUser(account),createdAt:account.createdAt},objectives:evidence(account.id),attempts:all('SELECT * FROM attempts WHERE userId=? ORDER BY createdAt DESC LIMIT 500',account.id).map(r=>({...r,response:parse(r.response)})),bktHistory:all('SELECT * FROM bkt_history WHERE userId=? ORDER BY createdAt DESC LIMIT 500',account.id).map(r=>({...r,data:parse(r.data)})),reviewHistory:all('SELECT * FROM reviews WHERE userId=? ORDER BY createdAt DESC LIMIT 500',account.id).map(r=>({...r,data:parse(r.data)})),vocabulary:all('SELECT * FROM vocabulary WHERE userId=?',account.id).map(r=>{const card=parse(r.card);card.due=new Date(card.due);if(card.last_review)card.last_review=new Date(card.last_review);return {...itemView(r),card,retrievability:card.last_review?scheduler.get_retrievability(card,new Date(),false):null};}),placement:placement(account),quotas:{uploads:quota(account.id,'uploads'),help:quota(account.id,'help')}}));});
  app.get('/api/admin/jobs',(req,res)=>res.json({jobs:all('SELECT * FROM jobs ORDER BY createdAt DESC LIMIT 200').map(r=>({...jobView(r),userId:r.userId}))}));
  app.get('/api/admin/activity',(req,res)=>{const rows=all('SELECT * FROM events ORDER BY createdAt DESC LIMIT 500').map(r=>redact({...r,data:parse(r.data)}));res.json({aiRuns:rows.filter(r=>r.kind==='ai'),transitions:rows.filter(r=>r.kind!=='ai')});});
  const reviewView=r=>redact({...r,data:parse(r.data),resolution:parse(r.resolution)});
  app.get('/api/admin/reviews',(req,res)=>res.json({reviews:all('SELECT * FROM review_queue ORDER BY createdAt DESC LIMIT 200').map(reviewView)}));
  app.patch('/api/admin/settings',(req,res)=>{if(typeof req.body.paused!=='boolean')fail(400,'INVALID_INPUT','paused must be true or false.');run("INSERT OR REPLACE INTO operational VALUES('paused',?)",String(req.body.paused));audit(req.user.id,'transition',{node:'operations',event:req.body.paused?'pause':'resume',to:req.body.paused?'paused':'active'});res.json({paused:paused()});});
  function validateProposal(proposal,book,passage,{requireReview=true}={}) {
    if(!proposal||!Array.isArray(proposal.lessons)||!proposal.lessons.length||proposal.lessons.length>12)fail(422,'INVALID_GENERATION','A curriculum must contain one to twelve lessons.');
    str(proposal.title,'Curriculum title',300);str(proposal.reason,'Curriculum reason',5000);const objectives=catalog().objectives,items=new Set();
    for(const lesson of proposal.lessons){str(lesson.title,'Lesson title',200);str(lesson.explanation,'Lesson explanation',15000);if(!Number.isInteger(lesson.estimatedMinutes)||lesson.estimatedMinutes<5||lesson.estimatedMinutes>8)fail(422,'INVALID_GENERATION','Each lesson must fit a five to eight minute session.');if(!Array.isArray(lesson.objectiveIds)||!lesson.objectiveIds.length||lesson.objectiveIds.some(id=>!objectives.some(o=>o.id===id)))fail(422,'UNKNOWN_OBJECTIVE','The proposed lesson uses an unregistered learning objective.');if(!Array.isArray(lesson.questions)||lesson.questions.length<2||lesson.questions.length>12||!lesson.questions.some(q=>q.type==='fresh-transfer')||!lesson.questions.some(q=>q.type==='target-comprehension'))fail(422,'INVALID_GENERATION','Each lesson needs two to twelve questions, including fresh transfer and target comprehension.');if(lesson.examples&&!Array.isArray(lesson.examples))fail(422,'INVALID_GENERATION','Lesson examples must be a list.');for(const example of lesson.examples||[]){str(example.es,'Spanish example',2000);str(example.en,'English example',2000);}for(const q of lesson.questions){str(q.id,'Question ID',120);str(q.prompt,'Question',3000);if(!['fresh-transfer','target-comprehension','target-form'].includes(q.type)||!['string','number'].includes(typeof q.version)||!String(q.version).trim()||!Array.isArray(q.choices)||q.choices.length<2||q.choices.length>6||q.choices.some(c=>typeof c!=='string'||!c.trim()||c.length>2000)||new Set(q.choices.map(normalized)).size!==q.choices.length||!Number.isInteger(q.answerIndex)||q.answerIndex<0||q.answerIndex>=q.choices.length)fail(422,'INVALID_GENERATION','A question has invalid type, version, choices, or answer key.');const objective=objectives.find(o=>o.id===q.objectiveId);if(!objective||String(objective.version||'1')!==String(q.objectiveVersion||'1')||!lesson.objectiveIds.includes(q.objectiveId))fail(422,'UNKNOWN_OBJECTIVE','A question does not match a registered objective version.');const source=passage.sentences.find(s=>s.id===q.sourceSpan?.sentenceId);if(!source||typeof q.sourceSpan.text!=='string'||!q.sourceSpan.text.trim()||!source.text.includes(q.sourceSpan.text))fail(422,'SOURCE_MISMATCH','A question is not grounded in the selected passage.');if(q.type==='fresh-transfer'&&(lesson.examples||[]).some(example=>normalized(q.prompt).includes(normalized(example.es))))fail(422,'INVALID_GENERATION','A fresh-transfer question repeats a taught example.');const identity=assessmentId(q);if(items.has(identity))fail(422,'DUPLICATE_ASSESSMENT','A generated curriculum repeats the same assessment item.');items.add(identity);str(q.explanation,'Answer explanation',5000);if(requireReview&&!isReviewed(q))fail(422,'SEMANTIC_REVIEW_REQUIRED','A generated question needs independent semantic review.');}}
    return proposal;
  }
  function acceptProposal(job,proposal,reviewer=null) {
    const user=one('SELECT * FROM users WHERE id=?',job.userId),book=bookFor(job.bookId,user),passage=passagesFor(book).find(c=>c.id===parse(job.input).passageId);
    if(!passage)fail(409,'PASSAGE_NOT_FOUND','The original source passage is no longer available. Request a new lesson for a current passage.');
    validateProposal(proposal,book,passage,{requireReview:!reviewer});
    const version=(one('SELECT max(version) AS n FROM curricula WHERE userId=? AND bookId=?',user.id,book.id)?.n||0)+1;
    const lessons=proposal.lessons.map((lesson,i)=>({...lesson,id:`${job.id}-l${i+1}`,bookId:book.id,passageId:passage.id,generated:true,questions:lesson.questions.map(q=>({...q,id:assessmentId(q),version:String(q.version),...(reviewer?{review:{status:'approved',reviewer,version:String(q.version),reason:'Human semantic review accepted this exact proposed version.'}}:{})}))}));
    const previous=curriculumFor(book,user),data={version,title:proposal.title,reason:proposal.reason,lessons:[...(previous?.lessons||[]).filter(l=>l.passageId!==passage.id),...lessons.map(l=>lessonSummary(l,user))]};
    for(const lesson of lessons)run('INSERT INTO lessons VALUES(?,?,?,?,?)',lesson.id,user.id,book.id,json(lesson),stamp());
    run('INSERT INTO curricula VALUES(?,?,?,?,?,?)',randomUUID(),user.id,book.id,version,json(data),stamp());audit(user.id,'curriculum',{version,bookId:book.id,reason:data.reason,lessonIds:lessons.map(l=>l.id),reviewer},job.id);return {curriculum:data};
  }
  app.post('/api/admin/reviews/:id/resolve',(req,res)=>{const row=one('SELECT * FROM review_queue WHERE id=?',req.params.id);if(!row)fail(404,'REVIEW_NOT_FOUND','Review not found.');if(row.status!=='pending')fail(409,'REVIEW_RESOLVED','This review has already been resolved.');const decision=req.body.decision,reason=redact(str(req.body.reason,'Resolution reason',3000));if(!['approve','reject'].includes(decision))fail(400,'INVALID_INPUT','Choose approve or reject.');transaction(()=>{let result=null,job=null;if(row.kind==='curriculum'){const data=parse(row.data);job=one('SELECT * FROM jobs WHERE id=?',data.jobId);if(!job||job.userId!==row.userId||job.bookId!==row.bookId||job.kind!=='curriculum')fail(409,'JOB_NOT_FOUND','The original job no longer exists.');if(decision==='approve')result=acceptProposal(job,data.proposal,req.user.id);const {status,...previous}=parse(job.result,{}),message=decision==='approve'?'A reviewed lesson is ready.':'This proposal was not approved. Your current lessons and reader are still available.';result={...previous,...result,reviewId:row.id,decision,message};run('UPDATE jobs SET result=?,message=?,updatedAt=? WHERE id=?',json(result),'Complete',stamp(),job.id);}run('UPDATE review_queue SET status=?,resolution=? WHERE id=?',decision==='approve'?'approved':'rejected',json({decision,reason,reviewer:req.user.id,createdAt:stamp(),result}),row.id);audit(req.user.id,'review_resolution',{reviewId:row.id,decision,reason,result},job?.id);});res.json({review:reviewView(one('SELECT * FROM review_queue WHERE id=?',row.id))});});
  app.delete('/api/account',auth,async(req,res)=>{if(active&&one('SELECT userId FROM jobs WHERE id=?',active.id)?.userId===req.user.id)active.controller.abort();const files=all('SELECT path FROM books WHERE userId=?',req.user.id).map(r=>r.path).filter(Boolean);transaction(()=>{run("DELETE FROM events WHERE jobId IN (SELECT id FROM jobs WHERE userId=?) OR (kind='review_resolution' AND CASE WHEN json_valid(data) THEN json_extract(data,'$.reviewId') END IN (SELECT id FROM review_queue WHERE userId=?))",req.user.id,req.user.id);run('DELETE FROM users WHERE id=?',req.user.id);});for(const path of files)rmSync(path,{force:true});res.clearCookie('comelibro_session',{path:'/'});res.json({ok:true});});
  app.use('/api',(req,res)=>res.status(404).json({error:'This endpoint does not exist.',code:'NOT_FOUND'}));
  const dist=join(root,'web','dist');if(existsSync(dist)){app.use(express.static(dist,{index:false}));app.get('/{*path}',(req,res)=>res.sendFile(join(dist,'index.html')));}
  app.use((error,req,res,next)=>{if(res.headersSent)return next(error);const status=error.type==='entity.too.large'?413:error.type==='entity.parse.failed'?400:error.status||500;res.status(status).json({error:status===500?'Something went wrong. Please try again.':status===413?'PDFs must be 5 MB or smaller.':status===400&&error.type==='entity.parse.failed'?'Send valid JSON.':error.message,code:error.code||(status===413?'FILE_TOO_LARGE':status===400?'INVALID_JSON':'INTERNAL_ERROR')});if(status===500&&env.NODE_ENV!=='test')console.error('Request failed:',error.name,error.message?.replace(/(?:Bearer|sk-)\S+/g,'[REDACTED]'));});
  run("UPDATE jobs SET status='failed',error='Processing was interrupted by a restart. Please try again.',updatedAt=? WHERE status='running'",stamp());
  run("UPDATE books SET status='failed' WHERE status='processing' AND id IN (SELECT bookId FROM jobs WHERE kind='upload' AND status='failed')");
  const cleanup=()=>{run('DELETE FROM events WHERE createdAt<?',new Date(Date.now()-30*86400000).toISOString());run('DELETE FROM sessions WHERE expiresAt<?',stamp());run('DELETE FROM tokens WHERE expiresAt<?',stamp());run('DELETE FROM throttles WHERE expiresAt<?',Date.now());};cleanup();const retention=setInterval(cleanup,86400000);retention.unref();
  async function processQueue() {
    if(workerRunning||paused())return;const job=one("SELECT * FROM jobs WHERE status='queued' ORDER BY createdAt,id LIMIT 1");if(!job)return;
    workerRunning=true;const controller=new AbortController();active={id:job.id,controller};const timeout=setTimeout(()=>controller.abort(new Error('Processing timed out. Please try again.')),180000);timeout.unref();
    const stillActive=()=>one('SELECT status FROM jobs WHERE id=?',job.id)?.status==='running'&&!controller.signal.aborted;
    const onProgress=(progress,message)=>{if(typeof progress==='object'){message=progress.message;progress=progress.progress;}if(stillActive())run('UPDATE jobs SET progress=?,message=?,updatedAt=? WHERE id=?',Math.max(0,Math.min(1,Number(progress)||0)),redact(String(message||'Processing…').slice(0,500)),stamp(),job.id);};
    if(!run("UPDATE jobs SET status='running',message='Processing…',updatedAt=? WHERE id=? AND status='queued'",stamp(),job.id).changes){clearTimeout(timeout);active=null;workerRunning=false;return;}audit(job.userId,'transition',{node:'job',event:'start',from:'queued',to:'running'},job.id);
    try {
      const input=parse(job.input);let result;
      if(job.kind==='upload') {
        const adapter=options.pdfAdapter||await import('./pdf.mjs');const extracted=await adapter.extractPdf({path:input.path,signal:controller.signal,onProgress});
        if(!Array.isArray(extracted.pages)||!extracted.pages.length||extracted.pages.length>10)fail(422,'INVALID_PAGES','PDFs must contain one to ten readable pages.');if(extracted.pages.some((p,i)=>p.page!==i+1||typeof p.text!=='string'||p.text.length>80000)||!extracted.pages.some(p=>p.text.trim()))fail(422,'UNREADABLE_PDF','The PDF text could not be read. Try a clearer scan or a text PDF.');
        if(!stillActive())return;const book=bookFor(job.bookId,{id:job.userId});const updated={...book,pages:extracted.pages,chapters:chaptersFromPages(book.id,extracted.pages),extractionWarnings:extracted.warnings||[]};run('UPDATE books SET data=?,status=? WHERE id=?',json(updated),'needs_confirmation',book.id);result={bookId:book.id,status:'needs_confirmation'};
      } else {
        if(!capabilities().ai&&!options.aiAdapter)fail(503,'AI_UNAVAILABLE','Live AI is currently unavailable. Existing lessons and reading remain available.');
        const adapter=options.aiAdapter||await import('./ai.mjs'),user=one('SELECT * FROM users WHERE id=?',job.userId),book=bookFor(job.bookId,user);
        const current=job.kind==='curriculum'&&curriculumFor(book,user),taskInput=job.kind==='help'?{book:{id:book.id,title:book.title},sentence:sourceSentence(book,input.sentenceId).sentence,kind:input.kind,word:input.word}:{book:{id:book.id,title:book.title},passage:passagesFor(book).find(c=>c.id===input.passageId),objectives:catalog().objectives,evidence:evidence(user.id).map(({id,version,probability,status,reason})=>({id,version,probability,status,reason})),currentCurriculum:current?{version:current.version,title:current.title}:null};
        const generated=redact(await adapter.runTask({kind:job.kind,input:taskInput,signal:controller.signal,onProgress,onEvent:event=>{if(one('SELECT id FROM users WHERE id=?',job.userId))audit(job.userId,'ai',event,job.id);}}));
        if(!stillActive())return;
        if(job.kind==='help'){str(generated.text,'AI help',16000);result={text:generated.text,generated:true};}
        else {try{validateProposal(generated,book,taskInput.passage);result=transaction(()=>acceptProposal(job,generated));}catch(error){const reviewId=randomUUID();run('INSERT INTO review_queue VALUES(?,?,?,?,?,?,?,?)',reviewId,job.userId,job.bookId,'curriculum','pending',json(redact({jobId:job.id,proposal:generated,reason:error.message})),null,stamp());result={status:'needs_review',reviewId,message:'This proposal needs review. Your current lessons and reader are still available.'};}}
      }
      if(stillActive()){run("UPDATE jobs SET status='completed',progress=1,message='Complete',result=?,updatedAt=? WHERE id=?",json(result),stamp(),job.id);audit(job.userId,'transition',{node:'job',event:'complete',from:'running',to:'completed'},job.id);}
    }catch(error){if(one('SELECT status FROM jobs WHERE id=?',job.id)?.status==='running'){const message=redact(controller.signal.aborted?'Processing timed out. Please try again.':error.code==='ERR_MODULE_NOT_FOUND'?'This processing service is unavailable. Please try again later.':String(error.message||'Processing failed. Please try again.').slice(0,500));run("UPDATE jobs SET status='failed',error=?,message='Processing stopped. Please try again.',updatedAt=? WHERE id=?",message,stamp(),job.id);if(job.kind==='upload')run("UPDATE books SET status='failed' WHERE id=?",job.bookId);audit(job.userId,'transition',{node:'job',event:'failure',from:'running',to:'failed',error:message},job.id);}}
    finally{clearTimeout(timeout);active=null;workerRunning=false;}
  }
  const interval=options.worker===false?null:setInterval(()=>void processQueue(),500);interval?.unref();
  return {app,db,processQueue,close:async()=>{if(interval)clearInterval(interval);clearInterval(retention);active?.controller.abort();while(workerRunning)await new Promise(r=>setTimeout(r,10));db.close();}};
}
