import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,writeFileSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../app.mjs';
import { updateBkt,readiness,MODEL } from '../models.mjs';
const origin='http://localhost:3300';
const question=i=>({id:`q${i}`,version:'1',objectiveId:'test-objective',objectiveVersion:'1',type:i%2?'target-comprehension':'fresh-transfer',prompt:'Choose the meaning of casa.',choices:['house','horse'],answerIndex:0,explanation:'Casa means house.',sourceSpan:{sentenceId:'sentence-1',text:'casa'},review:{status:'approved',reviewer:'independent-test-reviewer',version:'1',reason:'Synthetic fixture'}});
async function fixture(t,extra={}) {
 const dir=mkdtempSync(join(tmpdir(),'comelibro-test-')),contentDir=join(dir,'content');mkdirSync(contentDir);
 const catalog={objectives:[{id:'test-objective',version:'1',label:'Recognize casa',description:'Test only',cvc:[]}],placement:[question(1),question(2),question(3)],lessons:[{id:'lesson-1',bookId:'don-quixote',passageId:'chapter-1',title:'Opening',objectiveIds:['test-objective'],explanation:'Test content',examples:[],glossaryIds:['approved-word','pending-word'],questions:[question(4),question(5)]}],glossary:[{id:'approved-word',version:'1',term:'casa',meaning:'house',sourceId:'sentence-1',review:{status:'approved',reviewer:'independent-test-reviewer',version:'1'}},{id:'pending-word',version:'1',term:'pequeña',meaning:'small',sourceId:'sentence-1',review:{status:'pending',reviewer:null,version:'1'}}]};
 writeFileSync(join(contentDir,'catalog.json'),JSON.stringify(catalog));writeFileSync(join(contentDir,'don-quixote.json'),JSON.stringify({id:'don-quixote',title:'Test Don Quixote',author:'Cervantes',chapters:[{id:'chapter-1',title:'Chapter 1',tags:['authored-opening'],objectiveOccurrences:[{objectiveId:'authored-opening',count:1,locations:[{sentenceId:'sentence-1',text:'La casa'}]}],sentences:[{id:'sentence-1',text:'La casa es pequeña.',page:1,tags:['authored-opening'],objectiveSpans:[{objectiveId:'authored-opening',spans:['La casa']}]}]},{id:'long-chapter',title:'Long chapter',sentences:Array.from({length:85},(_,i)=>({id:`long-${i+1}`,text:`Oración ${i+1}.`,page:null,tags:[]}))}]}));
 const messages=[],options={dataDir:dir,contentDir,worker:false,env:{NODE_ENV:'test',APP_ORIGIN:origin,ADMIN_EMAILS:'admin@example.test'},mailSender:async message=>messages.push(message),...extra};let runtime=createApp(options);
 let server=runtime.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 t.after(async()=>{await new Promise(r=>server.close(r));await runtime.close();rmSync(dir,{recursive:true,force:true});});
 let base=`http://127.0.0.1:${server.address().port}`;
 async function restart(){await new Promise(r=>server.close(r));await runtime.close();runtime=createApp(options);server=runtime.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}`;}
 function client(){let cookie='',userId='';return async(path,method='GET',body,headers={})=>{const auth=['/api/auth/register','/api/auth/login','/api/auth/verify','/api/auth/forgot-password','/api/auth/reset-password'].includes(path),response=await fetch(base+path,{method,headers:{...(body!==undefined?{'content-type':'application/json'}:{}),...(method!=='GET'?{origin}:{}),...(cookie?{cookie}:{}),...(userId&&method!=='GET'&&!auth?{'x-expected-account-id':userId}:{}),...headers},body:body===undefined?undefined:Buffer.isBuffer(body)?body:JSON.stringify(body)});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];const result={status:response.status,body:await response.json(),headers:response.headers};if(result.body.user?.id)userId=result.body.user.id;if(['/api/auth/logout','/api/account'].includes(path)&&response.ok)userId='';return result;};}
 async function account(email='reader@example.test'){const api=client();assert.equal((await api('/api/auth/register','POST',{email,password:'correct horse battery staple',name:'Test Reader'})).status,201);const token=messages.at(-1).token;assert.equal((await api('/api/auth/verify','POST',{token})).status,200);return api;}
 async function place(api){await api('/api/placement/start','POST',{level:'elementary'});for(let i=1;i<=3;i++)assert.equal((await api('/api/placement/answer','POST',{questionId:`q${i}`,choiceIndex:0,attemptId:`placement-${i}`})).status,200);}
 return {get runtime(){return runtime;},restart,contentDir,client,account,place,messages,catalog};
}
test('BKT numerical update and readiness threshold are deterministic',()=>{assert.ok(Math.abs(updateBkt(.2,true)-.5368421052631579)<1e-12);assert.ok(Math.abs(updateBkt(.2,false)-.14838709677419354)<1e-12);assert.equal(readiness(null).status,'unknown');const row={probability:.95,successes:3,itemCount:2,updatedAt:new Date().toISOString()};assert.equal(readiness(row).status,'skip');assert.equal(readiness({...row,itemCount:1}).status,'teach');assert.equal(readiness({...row,updatedAt:'2020-01-01T00:00:00Z'}).status,'refresh');assert.equal(MODEL.version,'bkt-v1');});
test('auth verification reset, origin enforcement, placement resume, immutable evidence and assistance',async t=>{const f=await fixture(t),anon=f.client();assert.equal((await anon('/api/books/don-quixote')).status,200);assert.equal((await anon('/api/admin/accounts')).status,401);assert.equal((await anon('/api/auth/register','POST',{}, {origin:'https://evil.example'})).status,403);
 const api=await f.account();const bootstrap=(await api('/api/bootstrap')).body;assert.equal(bootstrap.user.verified,true);assert.equal(JSON.stringify(bootstrap).includes('password'),false);assert.equal((await api('/api/admin/accounts')).status,403);
 const start=await api('/api/placement/start','POST',{level:'elementary'});assert.equal(start.body.question.answerIndex,undefined);let result=await api('/api/placement/answer','POST',{questionId:'q1',choiceIndex:0,attemptId:'same-attempt-1'});assert.equal(result.body.scored,true);assert.equal(result.body.placement.index,1);const first=f.runtime.db.prepare('SELECT probability FROM objectives').get().probability;
 result=await api('/api/placement/answer','POST',{questionId:'q1',choiceIndex:0,attemptId:'same-attempt-1'});assert.equal(result.body.duplicate,true);assert.equal(f.runtime.db.prepare('SELECT probability FROM objectives').get().probability,first);assert.equal((await api('/api/placement/answer','POST',{questionId:'q1',choiceIndex:1,attemptId:'same-attempt-1'})).status,409);
 await api('/api/auth/logout','POST',{});assert.equal((await api('/api/placement')).status,401);await api('/api/auth/login','POST',{email:'reader@example.test',password:'correct horse battery staple'});assert.equal((await api('/api/placement')).body.index,1);for(let i=2;i<=3;i++)await api('/api/placement/answer','POST',{questionId:`q${i}`,choiceIndex:0,attemptId:`next-attempt-${i}`});assert.equal((await api('/api/bootstrap')).body.onboarding.status,'complete');
 const lesson=(await api('/api/lessons/lesson-1')).body.lesson;assert.equal(lesson.questions[0].answerIndex,undefined);assert.equal(lesson.questions[0].explanation,undefined);await api('/api/lessons/lesson-1/assist','POST',{questionId:'q4',kind:'reveal'});result=await api('/api/lessons/lesson-1/answer','POST',{questionId:'q4',choiceIndex:0,attemptId:'assisted-test-1',assisted:false});assert.equal(result.body.scored,false);assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM bkt_history').get().n,3);
 await api('/api/auth/forgot-password','POST',{email:'reader@example.test'});const token=f.messages.at(-1).token;assert.equal((await api('/api/auth/reset-password','POST',{token,password:'new correct horse battery staple'})).status,200);assert.equal((await api('/api/placement')).status,401);assert.equal((await api('/api/auth/reset-password','POST',{token,password:'new correct horse battery staple'})).status,400);});
test('scored reviewed lesson evidence creates one low-mastery FSRS card without feeding ratings back into BKT',async t=>{const f=await fixture(t),api=f.client();assert.equal((await api('/api/auth/demo','POST',{})).status,201);let lesson=(await api('/api/lessons/lesson-1')).body.lesson;
 let answer=await api('/api/lessons/lesson-1/answer','POST',{questionId:'q4',choiceIndex:0,attemptId:'review-source-1'});assert.equal(answer.body.scored,true);assert.equal(answer.body.objective.status,'teach');let reviews=(await api('/api/reviews')).body;assert.equal(reviews.dueCount,1);assert.equal(reviews.total,1);const [card]=reviews.items;assert.equal(card.front,'Choose the meaning of casa.');assert.equal(card.back,'house\n\nCasa means house.');assert.equal(card.bookId,'don-quixote');assert.equal(card.sentenceId,'sentence-1');
 answer=await api('/api/lessons/lesson-1/answer','POST',{questionId:'q4',choiceIndex:0,attemptId:'review-source-1'});assert.equal(answer.body.duplicate,true);assert.equal((await api('/api/reviews')).body.total,1);await api('/api/lessons/lesson-1/assist','POST',{questionId:'q5',kind:'hint'});answer=await api('/api/lessons/lesson-1/answer','POST',{questionId:'q5',choiceIndex:0,attemptId:'assisted-no-card'});assert.equal(answer.body.scored,false);assert.equal((await api('/api/reviews')).body.total,1);
 f.catalog.lessons[0].questions.push({...question(6),review:{status:'pending',reviewer:null,version:'1'}},question(7));writeFileSync(join(f.contentDir,'catalog.json'),JSON.stringify(f.catalog));await f.restart();lesson=(await api('/api/lessons/lesson-1')).body.lesson;assert.equal(lesson.questions.length,4);answer=await api('/api/lessons/lesson-1/answer','POST',{questionId:'q6',choiceIndex:0,attemptId:'unreviewed-no-card'});assert.equal(answer.body.scored,false);assert.equal((await api('/api/reviews')).body.total,1);
 const user=(await api('/api/bootstrap')).body.user;f.runtime.db.prepare('UPDATE objectives SET probability=.95,successes=3,itemCount=2,updatedAt=? WHERE userId=? AND objectiveId=?').run(new Date().toISOString(),user.id,'test-objective');answer=await api('/api/lessons/lesson-1/answer','POST',{questionId:'q7',choiceIndex:0,attemptId:'mastered-no-card'});assert.equal(answer.body.scored,true);assert.equal(answer.body.objective.status,'skip');assert.equal((await api('/api/reviews')).body.total,1);assert.equal((await api('/api/vocabulary','POST',{bookId:'don-quixote',sentenceId:'sentence-1',front:'casa',back:'house'})).status,404);
 const before={objectives:f.runtime.db.prepare('SELECT * FROM objectives WHERE userId=?').all(user.id),bkt:f.runtime.db.prepare('SELECT * FROM bkt_history WHERE userId=?').all(user.id)};const result=await api(`/api/reviews/${card.id}`,'POST',{rating:3,attemptId:'review-attempt-1'});assert.equal(result.status,200);assert.ok(Date.parse(result.body.item.due)>Date.now());assert.equal((await api(`/api/reviews/${card.id}`,'POST',{rating:3,attemptId:'review-attempt-1'})).body.duplicate,true);assert.deepEqual(f.runtime.db.prepare('SELECT * FROM objectives WHERE userId=?').all(user.id),before.objectives);assert.deepEqual(f.runtime.db.prepare('SELECT * FROM bkt_history WHERE userId=?').all(user.id),before.bkt);assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM reviews').get().n,1);const other=f.client();await other('/api/auth/demo','POST',{});assert.equal((await other(`/api/reviews/${card.id}`,'POST',{rating:3,attemptId:'other-review-1'})).status,404);});
test('durable upload jobs enforce ownership, idempotency, quota, confirmation and cancellation',async t=>{const f=await fixture(t,{pdfAdapter:{extractPdf:async()=>({pages:[{page:1,text:'La casa es pequeña.'},{page:2,text:''}],warnings:['Page 2 is blank.']})}}),api=await f.account();await f.place(api);const headers={'content-type':'application/pdf','x-filename':'sample.pdf','idempotency-key':'upload-request-1'};const bytes=Buffer.from('%PDF-1.7 test fixture');const upload=await api('/api/books/upload','POST',bytes,headers);assert.equal(upload.status,202,JSON.stringify(upload.body));const again=await api('/api/books/upload','POST',bytes,headers);assert.equal(again.body.job.id,upload.body.job.id);assert.equal((await api('/api/bootstrap')).body.quotas.uploads.used,1);await f.runtime.processQueue();const job=(await api(`/api/jobs/${upload.body.job.id}`)).body.job;assert.equal(job.status,'completed',JSON.stringify(job));assert.equal((await api(`/api/books/${upload.body.bookId}`)).body.book.status,'needs_confirmation');const confirmed=await api(`/api/books/${upload.body.bookId}/confirm`,'POST',{});assert.equal(confirmed.status,200);assert.equal(confirmed.body.book.pages.length,2);assert.equal(confirmed.body.book.chapters[1].sentences.length,0);assert.deepEqual((await api(`/api/books/${upload.body.bookId}/passages?chapter=${upload.body.bookId}-page-2`)).body.passages,[]);assert.equal((await api(`/api/books/${upload.body.bookId}/confirm`,'POST',{})).body.book.confirmedAt,confirmed.body.book.confirmedAt);assert.equal((await api(`/api/books/${upload.body.bookId}/confirm`,'POST',{pages:[{page:1,text:'Texto español corregido.'},{page:2,text:''}]})).body.code,'SOURCE_LOCKED');assert.equal((await api(`/api/books/${upload.body.bookId}`)).body.book.pages[0].text,'La casa es pequeña.');assert.equal((await api(`/api/books/${upload.body.bookId}/confirm`,'POST',{pages:[{page:1,text:''},{page:2,text:''}]})).status,400);
 const other=await f.account('other@example.test');assert.equal((await other(`/api/books/${upload.body.bookId}`)).status,404);assert.equal((await other(`/api/jobs/${upload.body.job.id}`)).status,404);assert.equal((await other(`/api/jobs/${upload.body.job.id}/cancel`,'POST',{})).status,404);
 for(let i=2;i<=3;i++){const up=await api('/api/books/upload','POST',bytes,{...headers,'idempotency-key':`upload-request-${i}`});assert.equal(up.status,202);assert.equal((await api(`/api/jobs/${up.body.job.id}/cancel`,'POST',{})).body.job.status,'cancelled');}assert.equal((await api('/api/books/upload','POST',bytes,{...headers,'idempotency-key':'upload-request-4'})).status,429);assert.equal((await api('/api/books/upload','POST',Buffer.from('invalid pdf'),headers)).status,422);});
test('generated uncertain assessments retain prior curriculum and resolve their original job',async t=>{
 const proposal={title:'Generated plan',reason:'Teach the selected passage.',lessons:[{title:'Read casa',objectiveIds:['test-objective'],explanation:'A house is a casa.',examples:[],estimatedMinutes:6,questions:[{...question(10),review:{status:'uncertain',reviewer:'independent',version:'1',reason:'Check alignment'}},{...question(11),review:{status:'uncertain',reviewer:'independent',version:'1',reason:'Check alignment'}}]}]};
 const f=await fixture(t,{aiAdapter:{runTask:async()=>proposal}}),api=await f.account();await f.place(api);
 const original=(await api('/api/books/don-quixote/curriculum','POST',{passageId:'chapter-1'})).body.job;await f.runtime.processQueue();
 assert.equal((await api(`/api/jobs/${original.id}`)).body.job.result.status,'needs_review');
 assert.equal((await api('/api/books/don-quixote/curriculum')).body.curriculum.lessons[0].id,'lesson-1');
 const other=await f.account('other@example.test');assert.equal((await other(`/api/jobs/${original.id}`)).status,404);
 const admin=await f.account('admin@example.test'),first=(await admin('/api/admin/reviews')).body.reviews[0];
 const rejected=await admin(`/api/admin/reviews/${first.id}/resolve`,'POST',{decision:'reject',reason:'The source wording is not accurate enough.'});
 assert.equal(rejected.status,200,JSON.stringify(rejected.body));assert.equal(rejected.body.review.status,'rejected');assert.equal(rejected.body.review.resolution.result.decision,'reject');
 const rejectedJob=(await api(`/api/jobs/${original.id}`)).body.job;
 assert.equal(rejectedJob.status,'completed');assert.equal(rejectedJob.result.status,undefined);assert.deepEqual(rejectedJob.result,{reviewId:first.id,decision:'reject',message:'This proposal was not approved. Your current lessons and reader are still available.'});
 assert.equal((await api('/api/books/don-quixote/curriculum')).body.curriculum.lessons[0].id,'lesson-1');
 assert.equal((await admin(`/api/admin/reviews/${first.id}/resolve`,'POST',{decision:'reject',reason:'Repeated click.'})).status,409);
 const held=(await api('/api/books/don-quixote/curriculum','POST',{passageId:'chapter-1'})).body.job;await f.runtime.processQueue();
 const second=(await admin('/api/admin/reviews')).body.reviews.find(r=>r.id!==first.id);
 const approved=await admin(`/api/admin/reviews/${second.id}/resolve`,'POST',{decision:'approve',reason:'Verified source, answer, Spanish accuracy and objective alignment.'});
 assert.equal(approved.status,200,JSON.stringify(approved.body));assert.equal(approved.body.review.status,'approved');assert.equal(approved.body.review.resolution.result.curriculum.version,1);
 const approvedJob=(await api(`/api/jobs/${held.id}`)).body.job;
 assert.equal(approvedJob.status,'completed');assert.equal(approvedJob.result.status,undefined);assert.equal(approvedJob.result.decision,'approve');assert.equal(approvedJob.result.reviewId,second.id);assert.equal(approvedJob.result.curriculum.version,1);assert.equal(approvedJob.result.message,'A reviewed lesson is ready.');assert.equal(f.runtime.db.prepare("SELECT jobId FROM events WHERE kind='review_resolution' AND jobId=?").get(held.id).jobId,held.id);
 assert.notEqual((await api('/api/books/don-quixote/curriculum')).body.curriculum.lessons[0].id,'lesson-1');assert.equal((await admin('/api/admin/accounts')).status,200);
});
test('accepted generated anchors annotate only the current account curriculum without awarding mastery',async t=>{let next={version:'1',status:'approved',sentence:0};const proposal=input=>{const source=input.passage.sentences[next.sentence],span=source.text.includes('casa')?'casa':source.text.includes('perro')?'perro':'Oración';return {title:'Generated annotations',reason:'Teach one reviewed source construction.',lessons:[{title:'Reviewed anchor',objectiveIds:['test-objective'],explanation:'Practice the reviewed construction.',examples:[],estimatedMinutes:6,questions:Array.from({length:4},(_,i)=>({...question(30+i),id:`local-${i+1}`,version:next.version,type:i===0?'fresh-transfer':i===1?'target-comprehension':'target-form',prompt:`Reviewed question ${i+1} for ${span}.`,sourceSpan:{sentenceId:source.id,text:span},review:{status:next.status,reviewer:'annotation-reviewer',version:next.version,reason:'Exact source and objective checked.'}}))}]};};const f=await fixture(t,{pdfAdapter:{extractPdf:async()=>({pages:[{page:1,text:'La casa es pequeña. El perro corre.'}],warnings:[]})},aiAdapter:{runTask:async({input})=>proposal(input)}}),api=await f.account();await f.place(api);const beforeObjectives=JSON.stringify(f.runtime.db.prepare('SELECT * FROM objectives ORDER BY objectiveId,version').all()),beforeBkt=f.runtime.db.prepare('SELECT count(*) AS n FROM bkt_history').get().n,bytes=Buffer.from('%PDF-1.7 annotation fixture'),upload=await api('/api/books/upload','POST',bytes,{'content-type':'application/pdf','x-filename':'annotations.pdf','idempotency-key':'annotation-upload'});await f.runtime.processQueue();await api(`/api/books/${upload.body.bookId}/confirm`,'POST',{});const passageId=`${upload.body.bookId}-page-1`;
 const generate=async()=>{const queued=await api(`/api/books/${upload.body.bookId}/curriculum`,'POST',{passageId});await f.runtime.processQueue();return (await api(`/api/jobs/${queued.body.job.id}`)).body.job;};await generate();let book=(await api(`/api/books/${upload.body.bookId}`)).body.book,chapter=book.chapters[0],[first,unknown]=chapter.sentences,passage=(await api(`/api/books/${upload.body.bookId}/passages`)).body.passages[0];assert.deepEqual(first.tags,['test-objective']);assert.deepEqual(first.objectiveSpans,[{objectiveId:'test-objective',spans:['casa']}]);assert.equal(first.annotationProvenance.length,4);assert.deepEqual([...new Set(first.annotationProvenance.map(p=>p.curriculumVersion))],[1]);assert.deepEqual(first.annotationProvenance[0].review,{status:'approved',reviewer:'annotation-reviewer',version:'1'});assert.equal(/answerIndex|choices|explanation|reason|prompt/.test(JSON.stringify(first.annotationProvenance)),false);assert.deepEqual(unknown.tags,[]);assert.deepEqual(unknown.objectiveSpans,[]);assert.deepEqual(unknown.annotationProvenance,[]);assert.deepEqual(chapter.objectiveOccurrences,[{objectiveId:'test-objective',count:1,locations:[{sentenceId:first.id,text:'casa'}]}]);assert.deepEqual(passage.objectiveOccurrences,chapter.objectiveOccurrences);
 next={version:'2',status:'approved',sentence:0};await generate();book=(await api(`/api/books/${upload.body.bookId}`)).body.book;first=book.chapters[0].sentences[0];assert.deepEqual(first.objectiveSpans,[{objectiveId:'test-objective',spans:['casa']}]);assert.equal(first.annotationProvenance.length,4);assert.deepEqual([...new Set(first.annotationProvenance.map(p=>p.curriculumVersion))],[2]);assert.deepEqual([...new Set(first.annotationProvenance.map(p=>p.questionVersion))],['2']);const current=JSON.parse(f.runtime.db.prepare('SELECT data FROM curricula WHERE userId=(SELECT userId FROM books WHERE id=?) AND bookId=? ORDER BY version DESC LIMIT 1').get(upload.body.bookId,upload.body.bookId).data),lessonId=current.lessons[0].id,lessonRow=f.runtime.db.prepare('SELECT data,userId,bookId,createdAt FROM lessons WHERE id=?').get(lessonId),stored=JSON.parse(lessonRow.data),save=value=>f.runtime.db.prepare('UPDATE lessons SET data=? WHERE id=?').run(JSON.stringify(value),lessonId);const stale={...stored,id:'stale-reviewed-lesson',questions:stored.questions.map(q=>({...q,sourceSpan:{sentenceId:`${upload.body.bookId}-p1-s2`,text:'perro'}}))};f.runtime.db.prepare('INSERT INTO lessons VALUES(?,?,?,?,?)').run(stale.id,lessonRow.userId,lessonRow.bookId,JSON.stringify(stale),lessonRow.createdAt);assert.deepEqual((await api(`/api/books/${upload.body.bookId}`)).body.book.chapters[0].sentences[1].objectiveSpans,[]);save({...stored,questions:stored.questions.map(q=>({...q,objectiveVersion:'999'}))});assert.deepEqual((await api(`/api/books/${upload.body.bookId}`)).body.book.chapters[0].sentences[0].objectiveSpans,[]);save({...stored,questions:stored.questions.map(q=>({...q,review:{...q.review,status:'uncertain'}}))});assert.deepEqual((await api(`/api/books/${upload.body.bookId}`)).body.book.chapters[0].sentences[0].objectiveSpans,[]);save({...stored,questions:stored.questions.map(q=>({...q,sourceSpan:{...q.sourceSpan,text:'CASA'}}))});assert.deepEqual((await api(`/api/books/${upload.body.bookId}`)).body.book.chapters[0].sentences[0].objectiveSpans,[]);save(stored);
 next={version:'3',status:'uncertain',sentence:1};const held=await generate();assert.equal(held.result.status,'needs_review');const admin=await f.account('admin@example.test'),review=(await admin('/api/admin/reviews')).body.reviews.find(r=>r.id===held.result.reviewId);assert.equal((await admin(`/api/admin/reviews/${review.id}/resolve`,'POST',{decision:'reject',reason:'The proposed anchor was not approved.'})).status,200);book=(await api(`/api/books/${upload.body.bookId}`)).body.book;assert.deepEqual(book.chapters[0].sentences[1].objectiveSpans,[]);assert.deepEqual([...new Set(book.chapters[0].sentences[0].annotationProvenance.map(p=>p.curriculumVersion))],[2]);assert.equal((await api(`/api/books/${upload.body.bookId}`)).status,200);const other=await f.account('annotation-other@example.test');assert.equal((await other(`/api/books/${upload.body.bookId}`)).status,404);
 next={version:'1',status:'approved',sentence:0};const dq=await api('/api/books/don-quixote/curriculum','POST',{passageId:'long-chapter-window-1'});await f.runtime.processQueue();assert.equal((await api(`/api/jobs/${dq.body.job.id}`)).body.job.status,'completed');const reader=(await api('/api/books/don-quixote')).body.book,long=reader.chapters.find(c=>c.id==='long-chapter'),opening=reader.chapters.find(c=>c.id==='chapter-1');assert.deepEqual(opening.sentences[0].tags,['authored-opening']);assert.deepEqual(opening.sentences[0].objectiveSpans,[{objectiveId:'authored-opening',spans:['La casa']}]);assert.deepEqual(long.sentences[0].objectiveSpans,[{objectiveId:'test-objective',spans:['Oración']}]);assert.deepEqual(long.objectiveOccurrences,[{objectiveId:'test-objective',count:1,locations:[{sentenceId:'long-1',text:'Oración'}]}]);assert.deepEqual(long.sentences[1].objectiveSpans,[]);assert.deepEqual((await other('/api/books/don-quixote')).body.book.chapters.find(c=>c.id==='long-chapter').sentences[0].objectiveSpans,[]);const anonymous=(await f.client()('/api/books/don-quixote')).body.book.chapters.find(c=>c.id==='long-chapter').sentences[0];assert.equal(anonymous.objectiveSpans,undefined);assert.deepEqual(anonymous.tags,[]);assert.equal(JSON.stringify(f.runtime.db.prepare('SELECT * FROM objectives ORDER BY objectiveId,version').all()),beforeObjectives);assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM bkt_history').get().n,beforeBkt);});
test('help duplicate accounting, daily quota and admin pause are durable',async t=>{const f=await fixture(t,{aiAdapter:{runTask:async()=>({text:'Casa means house in this sentence.'})}}),api=await f.account();const input={sentenceId:'sentence-1',word:'casa',kind:'word'},headers={'idempotency-key':'help-request-1'};const help=await api('/api/books/don-quixote/help','POST',input,headers);assert.equal(help.status,202);assert.equal((await api('/api/books/don-quixote/help','POST',input,headers)).body.job.id,help.body.job.id);assert.equal((await api('/api/bootstrap')).body.quotas.help.used,1);await f.runtime.processQueue();assert.equal((await api(`/api/jobs/${help.body.job.id}`)).body.job.result.generated,true);const user=(await api('/api/bootstrap')).body.user;f.runtime.db.prepare("UPDATE quotas SET count=50 WHERE userId=? AND kind='help'").run(user.id);assert.equal((await api('/api/books/don-quixote/help','POST',input,{'idempotency-key':'help-request-2'})).status,429);assert.equal((await api('/api/books/don-quixote/help','POST',input,headers)).status,202);const admin=await f.account('admin@example.test');assert.equal((await admin('/api/admin/settings','PATCH',{paused:true})).body.paused,true);assert.equal((await api('/api/books/don-quixote/help','POST',input,{'idempotency-key':'help-request-3'})).body.code,'PROCESSING_PAUSED');assert.equal((await api('/api/books/don-quixote')).status,200);assert.equal((await api('/api/admin/settings','PATCH',{paused:false})).status,403);});
test('running cancellation rejects late output and account deletion clears private state',async t=>{let finish;const f=await fixture(t,{aiAdapter:{runTask:()=>new Promise(r=>{finish=r;})}}),api=await f.account();const job=(await api('/api/books/don-quixote/help','POST',{sentenceId:'sentence-1',word:'casa',kind:'word'})).body.job;const running=f.runtime.processQueue();await new Promise(r=>setTimeout(r,20));assert.equal((await api(`/api/jobs/${job.id}/cancel`,'POST',{})).body.job.status,'cancelled');finish({text:'Late output must not be published.'});await running;assert.equal((await api(`/api/jobs/${job.id}`)).body.job.result,null);assert.equal((await api('/api/account','DELETE',{})).status,200);assert.equal((await api('/api/bootstrap')).body.user,null);assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM users').get().n,0);assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM jobs').get().n,0);});
test('account deletion removes admin review copies for null-job feedback and owned jobs only',async t=>{const f=await fixture(t),learner=await f.account('learner@example.test'),other=await f.account('other@example.test'),admin=await f.account('admin@example.test'),db=f.runtime.db,learnerId=(await learner('/api/bootstrap')).body.user.id,otherId=(await other('/api/bootstrap')).body.user.id,adminId=(await admin('/api/bootstrap')).body.user.id,now=new Date().toISOString(),privateFeedback='PRIVATE_NULL_JOB_MARKER',privateJob='PRIVATE_JOB_MARKER',otherMarker='OTHER_LEARNER_MARKER';
 const feedback=(await learner('/api/feedback','POST',{message:privateFeedback})).body,jobId='learner-owned-curriculum-job',jobReviewId='learner-owned-curriculum-review';db.prepare('INSERT INTO jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(jobId,learnerId,'don-quixote','curriculum','completed',1,'Complete','{}','{}',null,'learner-deletion-test',now,now);db.prepare('INSERT INTO review_queue VALUES(?,?,?,?,?,?,?,?)').run(jobReviewId,learnerId,'don-quixote','curriculum','pending',JSON.stringify({jobId,proposal:{}}),null,now);
 assert.equal((await admin(`/api/admin/reviews/${feedback.id}/resolve`,'POST',{decision:'reject',reason:`Quoted ${privateFeedback}`})).status,200);assert.equal((await admin(`/api/admin/reviews/${jobReviewId}/resolve`,'POST',{decision:'reject',reason:`Quoted ${privateJob}`})).status,200);db.prepare('INSERT INTO events VALUES(?,?,?,?,?,?)').run('learner-owned-job-copy',adminId,jobId,'ai',JSON.stringify({message:privateJob}),now);
 const otherFeedback=(await other('/api/feedback','POST',{message:otherMarker})).body;assert.equal((await admin(`/api/admin/reviews/${otherFeedback.id}/resolve`,'POST',{decision:'reject',reason:`Quoted ${otherMarker}`})).status,200);assert.equal((await admin('/api/admin/settings','PATCH',{paused:true})).status,200);assert.match(JSON.stringify(db.prepare('SELECT * FROM events').all()),new RegExp(`${privateFeedback}|${privateJob}`));
 assert.equal((await learner('/api/account','DELETE',{})).status,200);const events=JSON.stringify(db.prepare('SELECT * FROM events').all());assert.doesNotMatch(events,new RegExp(`${privateFeedback}|${privateJob}`));assert.match(events,new RegExp(otherMarker));assert.equal(db.prepare('SELECT id FROM users WHERE id=?').get(learnerId),undefined);assert.equal(db.prepare('SELECT count(*) AS n FROM jobs WHERE userId=?').get(learnerId).n,0);assert.equal(db.prepare('SELECT count(*) AS n FROM review_queue WHERE userId=?').get(learnerId).n,0);assert.equal(db.prepare('SELECT count(*) AS n FROM events WHERE userId=?').get(learnerId).n,0);assert.equal(db.prepare('SELECT id FROM users WHERE id=?').get(otherId).id,otherId);assert.equal(db.prepare('SELECT id FROM users WHERE id=?').get(adminId).id,adminId);assert.equal(db.prepare('SELECT id FROM review_queue WHERE id=?').get(otherFeedback.id).id,otherFeedback.id);assert.equal(db.prepare("SELECT count(*) AS n FROM events WHERE kind='transition' AND userId=? AND json_extract(data,'$.node')='operations'").get(adminId).n,1);
});
test('admin email ownership is verified before authorization and password spaces survive login',async t=>{const f=await fixture(t),api=f.client();const password='  spaced correct horse battery  ';assert.equal((await api('/api/auth/register','POST',{email:'admin@example.test',password,name:'Admin'})).status,201);assert.equal((await api('/api/admin/accounts')).body.code,'EMAIL_UNVERIFIED');assert.equal((await api('/api/admin/settings','PATCH',{paused:true})).status,403);await api('/api/auth/verify','POST',{token:f.messages.at(-1).token});assert.equal((await api('/api/admin/accounts')).status,200);await api('/api/auth/logout','POST',{});assert.equal((await api('/api/auth/login','POST',{email:'admin@example.test',password})).status,200);await api('/api/auth/logout','POST',{});assert.equal((await api('/api/auth/login','POST',{email:'admin@example.test',password:password.trim()})).status,401);});

test('independent backend review: bounded passages, lesson state, upload binding and verified admin job control',async t=>{const f=await fixture(t,{pdfAdapter:{extractPdf:async()=>{throw new Error('Synthetic parser failure.');}},aiAdapter:{runTask:async()=>({text:'house'})}}),anon=f.client();const oversized=Buffer.alloc(5*1024*1024+1,65);oversized.set(Buffer.from('%PDF-'));assert.equal((await anon('/api/books/upload','POST',oversized,{'content-type':'application/pdf'})).status,401);const cookieClient=f.client(),registration=await cookieClient('/api/auth/register','POST',{email:'cookie@example.test',password:'correct horse battery staple',name:'Cookie test'}),setCookie=registration.headers.get('set-cookie');assert.match(setCookie,/HttpOnly/i);assert.match(setCookie,/SameSite=Lax/i);assert.match(setCookie,/Path=\//i);assert.doesNotMatch(setCookie,/;\s*Secure/i);
 const api=await f.account();await f.place(api);const bootstrap=(await api('/api/bootstrap')).body;assert.equal(bootstrap.capabilities.ai,false);const windows=(await api('/api/books/don-quixote/passages?chapter=long-chapter')).body.passages;assert.deepEqual(windows.map(p=>p.sentences.length),[40,40,5]);assert.deepEqual(windows.flatMap(p=>p.sentences.map(s=>s.id)),Array.from({length:85},(_,i)=>`long-${i+1}`));
 let curriculum=(await api('/api/books/don-quixote/curriculum')).body.curriculum;assert.equal(curriculum.lessons[0].status,'available');const lesson=(await api('/api/lessons/lesson-1')).body.lesson;assert.equal(lesson.questions[0].type,'fresh-transfer');assert.equal(lesson.questions[0].answerIndex,undefined);assert.deepEqual(lesson.glossary,[{id:'approved-word',version:'1',term:'casa',meaning:'house',sourceId:'sentence-1'}]);await api('/api/lessons/lesson-1/answer','POST',{questionId:'q4',choiceIndex:0,attemptId:'lesson-progress-1'});curriculum=(await api('/api/books/don-quixote/curriculum')).body.curriculum;assert.equal(curriculum.lessons[0].status,'in_progress');await api('/api/lessons/lesson-1/answer','POST',{questionId:'q5',choiceIndex:0,attemptId:'lesson-progress-2'});assert.equal((await api('/api/books/don-quixote/curriculum')).body.curriculum.lessons[0].status,'complete');
 const bytes=Buffer.from('%PDF-1.7 original'),headers={'content-type':'application/pdf','x-filename':'sample.pdf','idempotency-key':'bound-upload-1'},userId=bootstrap.user.id,yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);f.runtime.db.prepare('INSERT INTO quotas VALUES(?,?,?,?)').run(userId,yesterday,'uploads',3);assert.equal((await api('/api/books/upload','POST',bytes,{...headers,origin:'https://evil.example'})).status,403);const upload=await api('/api/books/upload','POST',bytes,headers);assert.equal(upload.status,202);assert.equal((await api('/api/books/upload','POST',Buffer.from('%PDF-1.7 different'),headers)).status,409);assert.equal((await api('/api/books/upload','POST',bytes,{...headers,'idempotency-key':'short'})).status,400);await f.runtime.processQueue();assert.equal((await api(`/api/jobs/${upload.body.job.id}`)).body.job.status,'failed');assert.equal((await api('/api/bootstrap')).body.quotas.uploads.used,1);
 const help=(await api('/api/books/don-quixote/help','POST',{sentenceId:'sentence-1',word:'casa',kind:'word'})).body.job;const other=await f.account('other@example.test');assert.equal((await other(`/api/jobs/${help.id}`)).status,404);const admin=f.client();await admin('/api/auth/register','POST',{email:'admin@example.test',password:'correct horse battery staple',name:'Admin'});assert.equal((await admin(`/api/jobs/${help.id}`)).status,404);await admin('/api/auth/verify','POST',{token:f.messages.at(-1).token});assert.equal((await admin(`/api/jobs/${help.id}`)).status,200);assert.equal((await admin(`/api/jobs/${help.id}/cancel`,'POST',{})).body.job.status,'cancelled');});

test('independent backend review: generated assessment identity, structure and redaction survive regeneration',async t=>{let curriculumCalls=0;const make=(flip=false,invalid=false,version='1')=>({title:'Generated plan',reason:'Bearer sensitive-value',lessons:[{title:'Read casa',objectiveIds:['test-objective'],explanation:'Practice casa.',examples:[],estimatedMinutes:6,questions:[{...question(20),id:'local-a',version,type:'fresh-transfer',choices:flip?['horse','house']:['house','horse'],answerIndex:flip?1:0,review:{status:'approved',reviewer:'independent',version,reason:'Reviewed'}},...(!invalid?[{...question(21),id:'local-b',version,type:'target-comprehension',prompt:'What does casa mean here?',review:{status:'approved',reviewer:'independent',version,reason:'Reviewed'}}]:[])]}]});const f=await fixture(t,{aiAdapter:{runTask:async({kind,onEvent})=>{onEvent({phase:'input',authorization:'sensitive-value',message:'Bearer sensitive-value'});if(kind==='help')throw new Error('Bearer sensitive-value');curriculumCalls++;return make(curriculumCalls===2,curriculumCalls===3,String(curriculumCalls));}}}),api=await f.account();await f.place(api);const user=(await api('/api/bootstrap')).body.user;f.runtime.db.prepare('INSERT INTO books VALUES(?,?,?,?,?,?)').run('second-book',user.id,JSON.stringify({id:'second-book',title:'Second book',author:'Test',chapters:[{id:'chapter-1',title:'Chapter 1',sentences:[{id:'sentence-1',text:'La casa es pequeña.',page:1,tags:[]}]}]}),'ready',null,new Date().toISOString());
 let queued=await api('/api/books/don-quixote/curriculum','POST',{passageId:'chapter-1'});await f.runtime.processQueue();let curriculum=(await api('/api/books/don-quixote/curriculum')).body.curriculum,first=await api(`/api/lessons/${curriculum.lessons[0].id}`),firstIds=first.body.lesson.questions.map(q=>q.id);assert.equal(curriculum.reason,'[REDACTED]');assert.equal((await api(`/api/lessons/${curriculum.lessons[0].id}/assist`,'POST',{questionId:firstIds[1],kind:'reveal'})).status,200);let answer=await api(`/api/lessons/${curriculum.lessons[0].id}/answer`,'POST',{questionId:firstIds[0],choiceIndex:0,attemptId:'generated-first-1'});assert.equal(answer.body.scored,true);const probability=answer.body.objective.probability;
 queued=await api('/api/books/second-book/curriculum','POST',{passageId:'chapter-1'});await f.runtime.processQueue();curriculum=(await api('/api/books/second-book/curriculum')).body.curriculum;const second=await api(`/api/lessons/${curriculum.lessons[0].id}`),secondIds=second.body.lesson.questions.map(q=>q.id);assert.deepEqual(secondIds,firstIds);assert.deepEqual(second.body.lesson.questions.map(q=>q.version),['2','2']);answer=await api(`/api/lessons/${curriculum.lessons[0].id}/answer`,'POST',{questionId:secondIds[0],choiceIndex:1,attemptId:'generated-second-1'});assert.equal(answer.body.scored,false);answer=await api(`/api/lessons/${curriculum.lessons[0].id}/answer`,'POST',{questionId:secondIds[1],choiceIndex:0,attemptId:'generated-second-assisted'});assert.equal(answer.body.scored,false);assert.equal(answer.body.assisted,undefined);assert.equal(f.runtime.db.prepare('SELECT questionVersion FROM assistance WHERE userId=? AND questionId=?').get(user.id,firstIds[1]).questionVersion,'1');assert.equal(f.runtime.db.prepare('SELECT questionVersion FROM attempts WHERE userId=? AND id=?').get(user.id,'generated-second-assisted').questionVersion,'2');assert.equal(f.runtime.db.prepare('SELECT probability FROM objectives WHERE userId=? AND objectiveId=?').get(user.id,'test-objective').probability,probability);
 queued=await api('/api/books/second-book/curriculum','POST',{passageId:'chapter-1'});await f.runtime.processQueue();assert.equal((await api(`/api/jobs/${queued.body.job.id}`)).body.job.result.status,'needs_review');const admin=await f.account('admin@example.test'),reviews=(await admin('/api/admin/reviews')).body.reviews;assert.equal((await admin(`/api/admin/reviews/${reviews[0].id}/resolve`,'POST',{decision:'approve',reason:'Attempted structural override.'})).status,422);const activity=JSON.stringify((await admin('/api/admin/activity')).body);assert.equal(activity.includes('sensitive-value'),false);const failed=await api('/api/books/don-quixote/help','POST',{sentenceId:'sentence-1',word:'casa',kind:'word'});await f.runtime.processQueue();const job=(await api(`/api/jobs/${failed.body.job.id}`)).body.job;assert.equal(job.status,'failed');assert.equal(job.error,'[REDACTED]');});

test('legacy generated exposure survives restart, regeneration and changed distractors without rewriting history',async t=>{
 for(const exposure of ['correct','incorrect','hint','reveal'])await t.test(exposure,async t=>{
  const proposal={title:'Regenerated plan',reason:'Equivalent assessment.',lessons:[{title:'Read casa',objectiveIds:['test-objective'],explanation:'Practice casa.',estimatedMinutes:6,questions:[{...question(20),version:'2',choices:['lake','house'],answerIndex:1,sourceSpan:{sentenceId:'sentence-1',text:'La casa'},review:{status:'approved',reviewer:'independent',version:'2'}},question(21)]}]};
  const f=await fixture(t,{aiAdapter:{runTask:async()=>proposal}}),api=await f.account();await f.place(api);const user=(await api('/api/bootstrap')).body.user;
  // Captured pre-repair fingerprint for question(20), not recomputed with the implementation under test.
  const legacyId='generated-b2318e442fd376c31a8ca1cc740b880c',legacy={...f.catalog.lessons[0],id:'legacy-lesson',generated:true,questions:[{...question(20),id:legacyId}]};
  f.runtime.db.prepare('INSERT INTO lessons VALUES(?,?,?,?,?)').run(legacy.id,user.id,legacy.bookId,JSON.stringify(legacy),new Date().toISOString());
  const oldAnswer={questionId:legacyId,choiceIndex:exposure==='incorrect'?1:0,attemptId:'legacy-answer-1'};
  if(['correct','incorrect'].includes(exposure))assert.equal((await api('/api/lessons/legacy-lesson/answer','POST',oldAnswer)).body.scored,true);
  else assert.equal((await api('/api/lessons/legacy-lesson/assist','POST',{questionId:legacyId,kind:exposure})).status,200);
  const history=()=>({attempts:f.runtime.db.prepare('SELECT * FROM attempts WHERE userId=? ORDER BY id').all(user.id),assistance:f.runtime.db.prepare('SELECT * FROM assistance WHERE userId=?').all(user.id),objectives:f.runtime.db.prepare('SELECT * FROM objectives WHERE userId=?').all(user.id),bkt:f.runtime.db.prepare('SELECT * FROM bkt_history WHERE userId=? ORDER BY id').all(user.id)}),before=history();
  await f.restart();assert.deepEqual(history(),before);
  const oldView=(await api('/api/lessons/legacy-lesson')).body;assert.equal(oldView.lesson.questions[0].id,legacyId);
  if(['correct','incorrect'].includes(exposure)){
   assert.equal(oldView.progress.answered,1);assert.equal(oldView.progress.responses[0].choiceIndex,oldAnswer.choiceIndex);
   const replay=await api('/api/lessons/legacy-lesson/answer','POST',oldAnswer);assert.equal(replay.body.duplicate,true);assert.equal(replay.body.scored,true);
   assert.equal((await api('/api/lessons/legacy-lesson/answer','POST',{...oldAnswer,choiceIndex:1-oldAnswer.choiceIndex})).status,409);
  }else assert.equal(oldView.progress.assistance[0].kind,exposure);
  async function generate(client){const queued=await client('/api/books/don-quixote/curriculum','POST',{passageId:'chapter-1'});assert.equal(queued.status,202);await f.runtime.processQueue();const curriculum=(await client('/api/books/don-quixote/curriculum')).body.curriculum;return (await client(`/api/lessons/${curriculum.lessons[0].id}`)).body;}
  const next=await generate(api),q=next.lesson.questions[0];assert.notEqual(q.id,legacyId);assert.equal(next.progress.answered,0,'Old choice indices must not complete a new presentation');
  if(['hint','reveal'].includes(exposure)){
   assert.equal(next.progress.assistance[0]?.kind,exposure,'Sticky assistance must be visible on regenerated items');
   if(exposure==='reveal')assert.equal(next.progress.assistance[0].answerIndex,1,'Reveals must use the current choice order');
  }
  assert.equal((await api(`/api/lessons/${next.lesson.id}/answer`,'POST',{questionId:q.id,choiceIndex:1,attemptId:'equivalent-answer',assisted:false})).body.scored,false);
  const after=history();assert.deepEqual(after.objectives,before.objectives);assert.deepEqual(after.bkt,before.bkt);assert.deepEqual(after.attempts.filter(a=>a.id!=='equivalent-answer'),before.attempts);assert.deepEqual(after.assistance,before.assistance);
  if(['hint','reveal'].includes(exposure))assert.equal(after.attempts.find(a=>a.id==='equivalent-answer').assisted,1);
  assert.equal((await api(`/api/lessons/${next.lesson.id}/answer`,'POST',{...oldAnswer,questionId:q.id,choiceIndex:1})).status,['correct','incorrect'].includes(exposure)?409:200);
  const other=await f.account('isolated@example.test');await f.place(other);assert.equal((await other('/api/lessons/legacy-lesson')).status,404);const separate=await generate(other);assert.deepEqual(separate.progress.assistance,[]);
  assert.equal((await other(`/api/lessons/${separate.lesson.id}/answer`,'POST',{questionId:separate.lesson.questions[0].id,choiceIndex:1,attemptId:'equivalent-answer'})).body.scored,true);
  if(exposure==='reveal'){
   await api(`/api/lessons/${next.lesson.id}/assist`,'POST',{questionId:q.id,kind:'hint'});
   assert.equal((await api(`/api/lessons/${next.lesson.id}`)).body.progress.assistance[0].kind,'reveal','An alias hint cannot downgrade a legacy reveal');
  }
 });
});

test('generated identity preserves assessed context and objective boundaries while collapsing distractor-only exposure',async t=>{
 let distractor='horse',objectiveId='test-objective',objectiveVersion='1';
 const f=await fixture(t,{aiAdapter:{runTask:async({input})=>({title:'Context checks',reason:'Test identity boundaries.',lessons:[{title:'Context checks',objectiveIds:[objectiveId],explanation:'Practice casa.',estimatedMinutes:6,questions:['fresh-transfer','target-comprehension','target-form'].map((type,i)=>({...question(20+i),type,objectiveId,objectiveVersion,choices:['house',distractor],sourceSpan:{sentenceId:input.passage.sentences[0].id,text:input.passage.sentences[0].text}}))}]})}}),api=await f.account();await f.place(api);const user=(await api('/api/bootstrap')).body.user;
 f.runtime.db.prepare('INSERT INTO books VALUES(?,?,?,?,?,?)').run('different-context',user.id,JSON.stringify({id:'different-context',title:'Different context',chapters:[{id:'chapter-1',sentences:[{id:'other-sentence',text:'La casa es grande.'}]}]}),'ready',null,new Date().toISOString());
 const legacy={...f.catalog.lessons[0],id:'legacy-context',generated:true,questions:[{...question(20),id:'generated-40f351bf0f960c9ad921ef7920f556aa'},{...question(22),id:'generated-38033710ad57788bb4112a0e27bdfa44',type:'target-form'}].map(q=>({...q,sourceSpan:{sentenceId:'sentence-1',text:'La casa es pequeña.'}}))};
 f.runtime.db.prepare('INSERT INTO lessons VALUES(?,?,?,?,?)').run(legacy.id,user.id,legacy.bookId,JSON.stringify(legacy),new Date().toISOString());
 assert.equal((await api('/api/lessons/legacy-context/assist','POST',{questionId:legacy.questions[1].id,kind:'reveal'})).status,200);await f.restart();
 async function generate(book){const queued=await api(`/api/books/${book}/curriculum`,'POST',{passageId:'chapter-1'});assert.equal(queued.status,202);await f.runtime.processQueue();const curriculum=(await api(`/api/books/${book}/curriculum`)).body.curriculum;return (await api(`/api/lessons/${curriculum.lessons[0].id}`)).body.lesson;}
 async function answer(lesson,label){const scores=[];for(const [i,q] of lesson.questions.entries()){const result=await api(`/api/lessons/${lesson.id}/answer`,'POST',{questionId:q.id,choiceIndex:0,attemptId:`${label}-answer-${i}`});assert.equal(result.status,200);scores.push(result.body.scored);}return scores;}
 const original=await generate('don-quixote');assert.deepEqual(await answer(original,'original'),[true,true,false]);
 assert.equal((await api('/api/lessons/legacy-context/answer','POST',{questionId:legacy.questions[0].id,choiceIndex:0,attemptId:'new-before-legacy'})).body.scored,false,'New evidence also prevents credit through an unanswered old lesson');
 const changedSource=await generate('different-context');assert.equal(changedSource.questions[0].id,original.questions[0].id);assert.notEqual(changedSource.questions[1].id,original.questions[1].id);assert.notEqual(changedSource.questions[2].id,original.questions[2].id);assert.deepEqual(await answer(changedSource,'context'),[false,true,true]);
 distractor='lake';const changedChoices=await generate('different-context');assert.deepEqual(changedChoices.questions.map(q=>q.id),changedSource.questions.map(q=>q.id));assert.deepEqual(await answer(changedChoices,'distractors'),[false,false,false]);
 await api(`/api/lessons/${changedChoices.id}/assist`,'POST',{questionId:changedChoices.questions[0].id,kind:'hint'});
 objectiveVersion='2';f.catalog.objectives[0].version='2';writeFileSync(join(f.contentDir,'catalog.json'),JSON.stringify(f.catalog));await f.restart();const changedVersion=await generate('different-context');assert.notEqual(changedVersion.questions[0].id,changedChoices.questions[0].id);assert.deepEqual(await answer(changedVersion,'version'),[true,true,true]);
 objectiveId='different-objective';f.catalog.objectives.push({...f.catalog.objectives[0],id:objectiveId});writeFileSync(join(f.contentDir,'catalog.json'),JSON.stringify(f.catalog));await f.restart();const changedObjective=await generate('different-context');assert.notEqual(changedObjective.questions[0].id,changedVersion.questions[0].id);assert.deepEqual(await answer(changedObjective,'objective'),[true,true,true]);assert.deepEqual(await answer(original,'old-version'),[false,false,false]);
});
