import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,writeFileSync,rmSync,chmodSync,existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { createApp } from '../app.mjs';

const origin='http://localhost:3300',now=()=>new Date().toISOString();
const documentPlan=pages=>{const first=pages.find(page=>page.text.trim());return {edits:[],sections:[{title:'Document',page:first.page,anchor:first.text.trim()}]};};
function user(db,id){db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?,?,?)').run(id,`${id}@example.test`,id,'test-password',1,'learner','{}',JSON.stringify({status:'complete'}),now());const token=`${id}-session`;db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(createHash('sha256').update(token).digest('hex'),id,new Date(Date.now()+86400000).toISOString());return token;}
async function fixture(t,extra={}) {const dir=mkdtempSync(join(tmpdir(),'comelibro-private-source-')),contentDir=join(dir,'content');mkdirSync(contentDir);writeFileSync(join(contentDir,'catalog.json'),JSON.stringify({objectives:[{id:'fixture-objective',version:'1',label:'Fixture',description:'Fixture objective.',cvc:[]}],placement:[{id:'fixture-question',version:'1',objectiveId:'fixture-objective',objectiveVersion:'1',type:'multiple-choice',prompt:'Fixture?',choices:['Yes','No'],answerIndex:0}],lessons:[{id:'fixture-lesson',bookId:'don-quixote',title:'Fixture',objectiveIds:['fixture-objective'],questions:[]}]}));writeFileSync(join(contentDir,'don-quixote.json'),JSON.stringify({id:'don-quixote',title:'Public',author:'Test',chapters:[{id:'fixture-chapter',title:'Fixture',sentences:[{id:'fixture-sentence',text:'La casa es pequeña.',tags:[]}]}]}));const runtime=createApp({dataDir:dir,contentDir,worker:false,env:{NODE_ENV:'test',APP_ORIGIN:origin},...extra}),server=runtime.app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(async()=>{await new Promise(resolve=>server.close(resolve));await runtime.close();chmodSync(join(dir,'uploads'),0o700);rmSync(dir,{recursive:true,force:true});});const base=`http://127.0.0.1:${server.address().port}`;return {dir,runtime,request:async(id,path,method='GET',body,headers={})=>{const response=await fetch(base+path,{method,headers:{...(method==='GET'?{}:{origin,'x-expected-account-id':id}),cookie:`comelibro_session=${id}-session`,...(body instanceof Buffer?{'content-type':'application/pdf'}:body===undefined?{}:{'content-type':'application/json'}),...headers},body:body===undefined?undefined:body instanceof Buffer?body:JSON.stringify(body)});return {status:response.status,body:await response.json()};}};}

test('processing private sentences cannot create durable references and structured IDs work when ready',async t=>{const f=await fixture(t,{aiAdapter:{runTask:async()=>({text:'Synthetic help'})}});user(f.runtime.db,'owner');const bookId='private-book',oldId='draft-sentence';f.runtime.db.prepare('INSERT INTO books VALUES(?,?,?,?,?,?)').run(bookId,'owner',JSON.stringify({id:bookId,title:'Draft',pages:[{page:1,text:'Texto antiguo.'}],chapters:[{id:'draft-page',title:'Draft',sentences:[{id:oldId,text:'Texto antiguo.',page:1,tags:[]}]}]}),'processing',join(f.dir,'uploads','draft.pdf'),now());writeFileSync(join(f.dir,'uploads','draft.pdf'),'draft');
 assert.equal((await f.request('owner',`/api/books/${bookId}`)).body.book.chapters[0].sentences[0].id,oldId);
 for(const [path,body] of [[`/api/books/${bookId}/position`,{chapterId:'draft-page',sentenceId:oldId}],[`/api/books/${bookId}/help`,{sentenceId:oldId,kind:'translate'}],[`/api/books/${bookId}/curriculum`,{}]]){const result=await f.request('owner',path,'POST',body);assert.deepEqual({status:result.status,code:result.body.code},{status:409,code:'DOCUMENT_PROCESSING'});}
 assert.equal((await f.request('owner','/api/vocabulary','POST',{bookId,sentenceId:oldId,front:'texto',back:'text'})).status,404);
 assert.deepEqual({positions:f.runtime.db.prepare('SELECT count(*) AS n FROM positions').get().n,vocabulary:f.runtime.db.prepare('SELECT count(*) AS n FROM vocabulary').get().n,jobs:f.runtime.db.prepare('SELECT count(*) AS n FROM jobs').get().n,quotas:f.runtime.db.prepare('SELECT count(*) AS n FROM quotas').get().n},{positions:0,vocabulary:0,jobs:0,quotas:0});
 const currentId=`${bookId}-p1-s1`,ready={id:bookId,title:'Draft',rawPages:[{page:1,text:'El perro corre.'}],pages:[{page:1,text:'El perro corre.'}],chapters:[{id:`${bookId}-section-1`,title:'Document',sentences:[{id:currentId,text:'El perro corre.',page:1,tags:[]}]}],status:'ready'};f.runtime.db.prepare("UPDATE books SET data=?,status='ready' WHERE id=?").run(JSON.stringify(ready),bookId);
 assert.equal((await f.request('owner',`/api/books/${bookId}/position`,'POST',{chapterId:`${bookId}-section-1`,sentenceId:currentId})).status,200);assert.equal((await f.request('owner',`/api/books/${bookId}/help`,'POST',{sentenceId:currentId,kind:'word',word:'perro'})).status,202);assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM jobs WHERE kind=?').get('help').n,1);
});

test('feedback persists only owned structured sentence references',async t=>{const f=await fixture(t,{pdfAdapter:{extractPdf:async()=>({pages:[{page:1,text:'Texto antiguo.'}],warnings:[]})},aiAdapter:{runTask:async({input})=>documentPlan(input.pages)}});user(f.runtime.db,'owner');user(f.runtime.db,'sibling');const insert=(id,userId,data,status='ready')=>f.runtime.db.prepare('INSERT INTO books VALUES(?,?,?,?,?,?)').run(id,userId,JSON.stringify(data),status,null,now()),count=()=>f.runtime.db.prepare('SELECT count(*) AS n FROM review_queue').get().n,upload=await f.request('owner','/api/books/upload','POST',Buffer.from('%PDF-1.7 feedback fixture'),{'x-filename':'feedback.pdf','idempotency-key':'feedback-upload'}),bookId=upload.body.bookId;assert.equal(upload.status,202);await f.runtime.processQueue();const currentId=`${bookId}-p1-s1`;assert.equal((await f.request('owner',`/api/books/${bookId}`)).body.book.status,'ready');
 let result=await f.request('owner','/api/feedback','POST',{message:'The structured sentence needs review.',bookId,sentenceId:currentId});assert.equal(result.status,201);assert.equal(count(),1);
 assert.equal((await f.request('owner','/api/feedback','POST',{message:'The document needs review.',bookId})).status,201);assert.equal((await f.request('owner','/api/feedback','POST',{message:'General feedback.'})).status,201);result=await f.request('owner','/api/feedback','POST',{message:'Ungrounded sentence.',sentenceId:currentId});assert.deepEqual({status:result.status,code:result.body.code},{status:400,code:'INVALID_INPUT'});assert.equal(count(),3);
 assert.equal((await f.request('owner','/api/feedback','POST',{message:'The structured sentence is clear.',bookId,sentenceId:currentId})).status,201);assert.equal((await f.request('owner','/api/feedback','POST',{message:'The padded structured sentence is clear.',bookId,sentenceId:` ${currentId} `})).status,201);assert.equal(JSON.parse(f.runtime.db.prepare("SELECT data FROM review_queue WHERE bookId=? ORDER BY rowid DESC LIMIT 1").get(bookId).data).sentenceId,currentId);
 insert('other-book','owner',{id:'other-book',title:'Other',chapters:[{id:'other-page',sentences:[{id:'other-sentence',text:'Otra frase.',tags:[]}]}]});insert('sibling-book','sibling',{id:'sibling-book',title:'Sibling',chapters:[{id:'sibling-page',sentences:[{id:'sibling-sentence',text:'Otra frase.',tags:[]}]}]});for(const [body,expected] of [[{message:'Wrong sentence for this book.',bookId,sentenceId:'other-sentence'},'SENTENCE_NOT_FOUND'],[{message:'Other account book.',bookId:'sibling-book',sentenceId:'sibling-sentence'},'BOOK_NOT_FOUND']]){result=await f.request('owner','/api/feedback','POST',body);assert.deepEqual({status:result.status,code:result.body.code},{status:404,code:expected});}assert.equal(count(),5);
});

test('account deletion retains private metadata on denied unlink, then retries without late worker writes or sibling loss',async t=>{let release,startedResolve;const started=new Promise(resolve=>startedResolve=resolve),late=new Promise(resolve=>release=resolve);const f=await fixture(t,{pdfAdapter:{extractPdf:async()=>{startedResolve();await late;return {pages:[{page:1,text:'El perro corre.'}],warnings:[]};}},aiAdapter:{runTask:async({input})=>documentPlan(input.pages)}});user(f.runtime.db,'owner');user(f.runtime.db,'sibling');const siblingPath=join(f.dir,'uploads','sibling.pdf');writeFileSync(siblingPath,'sibling');f.runtime.db.prepare('INSERT INTO books VALUES(?,?,?,?,?,?)').run('sibling-book','sibling',JSON.stringify({id:'sibling-book',title:'Sibling',chapters:[]}),'ready',siblingPath,now());
 const upload=await f.request('owner','/api/books/upload','POST',Buffer.from('%PDF-1.7 private fixture'),{'x-filename':'private.pdf','idempotency-key':'private-upload'});assert.equal(upload.status,202);const worker=f.runtime.processQueue();await started;chmodSync(join(f.dir,'uploads'),0o500);const denied=await f.request('owner','/api/account','DELETE',{});assert.equal(denied.status,500);assert.equal((await f.request('owner','/api/bootstrap')).status,200);assert.ok(f.runtime.db.prepare('SELECT id FROM users WHERE id=?').get('owner'));assert.ok(f.runtime.db.prepare('SELECT path FROM books WHERE id=?').get(upload.body.bookId));assert.equal(f.runtime.db.prepare('SELECT status FROM jobs WHERE id=?').get(upload.body.job.id).status,'cancelled');assert.equal(existsSync(join(f.dir,'uploads',`${upload.body.bookId}.pdf`)),true);assert.ok(f.runtime.db.prepare('SELECT id FROM users WHERE id=?').get('sibling'));
 chmodSync(join(f.dir,'uploads'),0o700);assert.equal((await f.request('owner','/api/account','DELETE',{})).status,200);release();await worker;assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM users WHERE id=?').get('owner').n,0);assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM books WHERE userId=?').get('owner').n,0);assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM jobs WHERE userId=?').get('owner').n,0);assert.equal(f.runtime.db.prepare('SELECT count(*) AS n FROM events WHERE jobId=?').get(upload.body.job.id).n,0);assert.equal(existsSync(join(f.dir,'uploads',`${upload.body.bookId}.pdf`)),false);assert.ok(f.runtime.db.prepare('SELECT id FROM users WHERE id=?').get('sibling'));assert.equal(f.runtime.db.prepare('SELECT path FROM books WHERE id=?').get('sibling-book').path,siblingPath);assert.equal(existsSync(siblingPath),true);
});
